//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DataEpoch.proto
// Note: requires additional types generated from: EquipmentModelCommon.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoDataSample")]
  public partial class ProtoDataSample : global::ProtoBuf.IExtensible
  {
    public ProtoDataSample() {}
    

    private uint? _dataID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataID
    {
      get { return _dataID?? default(uint); }
      set { _dataID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataIDSpecified
    {
      get { return _dataID != null; }
      set { if (value == (_dataID== null)) _dataID = value ? dataID : (uint?)null; }
    }
    private bool ShouldSerializedataID() { return dataIDSpecified; }
    private void ResetdataID() { dataIDSpecified = false; }
    

    private long? _nativeValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nativeValue", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public long nativeValue
    {
      get { return _nativeValue?? default(long); }
      set { _nativeValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nativeValueSpecified
    {
      get { return _nativeValue != null; }
      set { if (value == (_nativeValue== null)) _nativeValue = value ? nativeValue : (long?)null; }
    }
    private bool ShouldSerializenativeValue() { return nativeValueSpecified; }
    private void ResetnativeValue() { nativeValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoDataSampleUx")]
  public partial class ProtoDataSampleUx : global::ProtoBuf.IExtensible
  {
    public ProtoDataSampleUx() {}
    

    private uint? _dataID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataID
    {
      get { return _dataID?? default(uint); }
      set { _dataID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataIDSpecified
    {
      get { return _dataID != null; }
      set { if (value == (_dataID== null)) _dataID = value ? dataID : (uint?)null; }
    }
    private bool ShouldSerializedataID() { return dataIDSpecified; }
    private void ResetdataID() { dataIDSpecified = false; }
    

    private uint? _repDomainID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"repDomainID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint repDomainID
    {
      get { return _repDomainID?? default(uint); }
      set { _repDomainID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool repDomainIDSpecified
    {
      get { return _repDomainID != null; }
      set { if (value == (_repDomainID== null)) _repDomainID = value ? repDomainID : (uint?)null; }
    }
    private bool ShouldSerializerepDomainID() { return repDomainIDSpecified; }
    private void ResetrepDomainID() { repDomainIDSpecified = false; }
    

    private uint? _colorSpace;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"colorSpace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colorSpace
    {
      get { return _colorSpace?? default(uint); }
      set { _colorSpace = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool colorSpaceSpecified
    {
      get { return _colorSpace != null; }
      set { if (value == (_colorSpace== null)) _colorSpace = value ? colorSpace : (uint?)null; }
    }
    private bool ShouldSerializecolorSpace() { return colorSpaceSpecified; }
    private void ResetcolorSpace() { colorSpaceSpecified = false; }
    

    private uint? _color;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint color
    {
      get { return _color?? default(uint); }
      set { _color = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool colorSpecified
    {
      get { return _color != null; }
      set { if (value == (_color== null)) _color = value ? color : (uint?)null; }
    }
    private bool ShouldSerializecolor() { return colorSpecified; }
    private void Resetcolor() { colorSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoRankLocationSample")]
  public partial class ProtoRankLocationSample : global::ProtoBuf.IExtensible
  {
    public ProtoRankLocationSample() {}
    

    private uint? _rankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankID
    {
      get { return _rankID?? default(uint); }
      set { _rankID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankIDSpecified
    {
      get { return _rankID != null; }
      set { if (value == (_rankID== null)) _rankID = value ? rankID : (uint?)null; }
    }
    private bool ShouldSerializerankID() { return rankIDSpecified; }
    private void ResetrankID() { rankIDSpecified = false; }
    

    private com.deere.proto.ProtoGPSPosition _dropPoint = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dropPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition dropPoint
    {
      get { return _dropPoint; }
      set { _dropPoint = value; }
    }

    private double? _implement_heading_arcdeg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"implement_heading_arcdeg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double implement_heading_arcdeg
    {
      get { return _implement_heading_arcdeg?? default(double); }
      set { _implement_heading_arcdeg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool implement_heading_arcdegSpecified
    {
      get { return _implement_heading_arcdeg != null; }
      set { if (value == (_implement_heading_arcdeg== null)) _implement_heading_arcdeg = value ? implement_heading_arcdeg : (double?)null; }
    }
    private bool ShouldSerializeimplement_heading_arcdeg() { return implement_heading_arcdegSpecified; }
    private void Resetimplement_heading_arcdeg() { implement_heading_arcdegSpecified = false; }
    

    private bool? _in_reverse;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"in_reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool in_reverse
    {
      get { return _in_reverse?? default(bool); }
      set { _in_reverse = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool in_reverseSpecified
    {
      get { return _in_reverse != null; }
      set { if (value == (_in_reverse== null)) _in_reverse = value ? in_reverse : (bool?)null; }
    }
    private bool ShouldSerializein_reverse() { return in_reverseSpecified; }
    private void Resetin_reverse() { in_reverseSpecified = false; }
    

    private double? _yaw_rate_arcdeg_per_sec;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"yaw_rate_arcdeg_per_sec", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yaw_rate_arcdeg_per_sec
    {
      get { return _yaw_rate_arcdeg_per_sec?? default(double); }
      set { _yaw_rate_arcdeg_per_sec = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yaw_rate_arcdeg_per_secSpecified
    {
      get { return _yaw_rate_arcdeg_per_sec != null; }
      set { if (value == (_yaw_rate_arcdeg_per_sec== null)) _yaw_rate_arcdeg_per_sec = value ? yaw_rate_arcdeg_per_sec : (double?)null; }
    }
    private bool ShouldSerializeyaw_rate_arcdeg_per_sec() { return yaw_rate_arcdeg_per_secSpecified; }
    private void Resetyaw_rate_arcdeg_per_sec() { yaw_rate_arcdeg_per_secSpecified = false; }
    

    private double? _delta_distance_mm;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"delta_distance_mm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double delta_distance_mm
    {
      get { return _delta_distance_mm?? default(double); }
      set { _delta_distance_mm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool delta_distance_mmSpecified
    {
      get { return _delta_distance_mm != null; }
      set { if (value == (_delta_distance_mm== null)) _delta_distance_mm = value ? delta_distance_mm : (double?)null; }
    }
    private bool ShouldSerializedelta_distance_mm() { return delta_distance_mmSpecified; }
    private void Resetdelta_distance_mm() { delta_distance_mmSpecified = false; }
    

    private double? _speed_km_per_hr;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"speed_km_per_hr", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double speed_km_per_hr
    {
      get { return _speed_km_per_hr?? default(double); }
      set { _speed_km_per_hr = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool speed_km_per_hrSpecified
    {
      get { return _speed_km_per_hr != null; }
      set { if (value == (_speed_km_per_hr== null)) _speed_km_per_hr = value ? speed_km_per_hr : (double?)null; }
    }
    private bool ShouldSerializespeed_km_per_hr() { return speed_km_per_hrSpecified; }
    private void Resetspeed_km_per_hr() { speed_km_per_hrSpecified = false; }
    

    private com.deere.proto.ProtoGPSPosition _left = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"left", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition left
    {
      get { return _left; }
      set { _left = value; }
    }

    private com.deere.proto.ProtoGPSPosition _right = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"right", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition right
    {
      get { return _right; }
      set { _right = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoGPSSample")]
  public partial class ProtoGPSSample : global::ProtoBuf.IExtensible
  {
    public ProtoGPSSample() {}
    

    private uint? _receiverID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"receiverID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint receiverID
    {
      get { return _receiverID?? default(uint); }
      set { _receiverID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool receiverIDSpecified
    {
      get { return _receiverID != null; }
      set { if (value == (_receiverID== null)) _receiverID = value ? receiverID : (uint?)null; }
    }
    private bool ShouldSerializereceiverID() { return receiverIDSpecified; }
    private void ResetreceiverID() { receiverIDSpecified = false; }
    

    private com.deere.proto.ProtoGPSPosition _gpsPosition = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gpsPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition gpsPosition
    {
      get { return _gpsPosition; }
      set { _gpsPosition = value; }
    }

    private double? _GPSHeading;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"GPSHeading", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double GPSHeading
    {
      get { return _GPSHeading?? default(double); }
      set { _GPSHeading = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GPSHeadingSpecified
    {
      get { return _GPSHeading != null; }
      set { if (value == (_GPSHeading== null)) _GPSHeading = value ? GPSHeading : (double?)null; }
    }
    private bool ShouldSerializeGPSHeading() { return GPSHeadingSpecified; }
    private void ResetGPSHeading() { GPSHeadingSpecified = false; }
    

    private com.deere.proto.EDifferentialType? _DifferentialType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"DifferentialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDifferentialType DifferentialType
    {
      get { return _DifferentialType?? com.deere.proto.EDifferentialType.DT_UNDEFINED; }
      set { _DifferentialType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DifferentialTypeSpecified
    {
      get { return _DifferentialType != null; }
      set { if (value == (_DifferentialType== null)) _DifferentialType = value ? DifferentialType : (com.deere.proto.EDifferentialType?)null; }
    }
    private bool ShouldSerializeDifferentialType() { return DifferentialTypeSpecified; }
    private void ResetDifferentialType() { DifferentialTypeSpecified = false; }
    

    private double? _elevation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"elevation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double elevation
    {
      get { return _elevation?? default(double); }
      set { _elevation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool elevationSpecified
    {
      get { return _elevation != null; }
      set { if (value == (_elevation== null)) _elevation = value ? elevation : (double?)null; }
    }
    private bool ShouldSerializeelevation() { return elevationSpecified; }
    private void Resetelevation() { elevationSpecified = false; }
    

    private bool? _inReverse;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"inReverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool inReverse
    {
      get { return _inReverse?? default(bool); }
      set { _inReverse = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool inReverseSpecified
    {
      get { return _inReverse != null; }
      set { if (value == (_inReverse== null)) _inReverse = value ? inReverse : (bool?)null; }
    }
    private bool ShouldSerializeinReverse() { return inReverseSpecified; }
    private void ResetinReverse() { inReverseSpecified = false; }
    

    private double? _yawRate;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"yawRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double yawRate
    {
      get { return _yawRate?? default(double); }
      set { _yawRate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool yawRateSpecified
    {
      get { return _yawRate != null; }
      set { if (value == (_yawRate== null)) _yawRate = value ? yawRate : (double?)null; }
    }
    private bool ShouldSerializeyawRate() { return yawRateSpecified; }
    private void ResetyawRate() { yawRateSpecified = false; }
    

    private double? _distance;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double distance
    {
      get { return _distance?? default(double); }
      set { _distance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool distanceSpecified
    {
      get { return _distance != null; }
      set { if (value == (_distance== null)) _distance = value ? distance : (double?)null; }
    }
    private bool ShouldSerializedistance() { return distanceSpecified; }
    private void Resetdistance() { distanceSpecified = false; }
    

    private double? _gpsSpeed;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"gpsSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double gpsSpeed
    {
      get { return _gpsSpeed?? default(double); }
      set { _gpsSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gpsSpeedSpecified
    {
      get { return _gpsSpeed != null; }
      set { if (value == (_gpsSpeed== null)) _gpsSpeed = value ? gpsSpeed : (double?)null; }
    }
    private bool ShouldSerializegpsSpeed() { return gpsSpeedSpecified; }
    private void ResetgpsSpeed() { gpsSpeedSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoGPSSampleExtended")]
  public partial class ProtoGPSSampleExtended : global::ProtoBuf.IExtensible
  {
    public ProtoGPSSampleExtended() {}
    

    private uint? _receiverID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"receiverID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint receiverID
    {
      get { return _receiverID?? default(uint); }
      set { _receiverID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool receiverIDSpecified
    {
      get { return _receiverID != null; }
      set { if (value == (_receiverID== null)) _receiverID = value ? receiverID : (uint?)null; }
    }
    private bool ShouldSerializereceiverID() { return receiverIDSpecified; }
    private void ResetreceiverID() { receiverIDSpecified = false; }
    

    private com.deere.proto.ProtoGPSPosition _gpsPosition = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gpsPosition", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition gpsPosition
    {
      get { return _gpsPosition; }
      set { _gpsPosition = value; }
    }

    private double? _Heading;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Heading", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Heading
    {
      get { return _Heading?? default(double); }
      set { _Heading = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool HeadingSpecified
    {
      get { return _Heading != null; }
      set { if (value == (_Heading== null)) _Heading = value ? Heading : (double?)null; }
    }
    private bool ShouldSerializeHeading() { return HeadingSpecified; }
    private void ResetHeading() { HeadingSpecified = false; }
    

    private uint? _AccuracyIndicator;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"AccuracyIndicator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccuracyIndicator
    {
      get { return _AccuracyIndicator?? default(uint); }
      set { _AccuracyIndicator = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccuracyIndicatorSpecified
    {
      get { return _AccuracyIndicator != null; }
      set { if (value == (_AccuracyIndicator== null)) _AccuracyIndicator = value ? AccuracyIndicator : (uint?)null; }
    }
    private bool ShouldSerializeAccuracyIndicator() { return AccuracyIndicatorSpecified; }
    private void ResetAccuracyIndicator() { AccuracyIndicatorSpecified = false; }
    

    private double? _distance;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double distance
    {
      get { return _distance?? default(double); }
      set { _distance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool distanceSpecified
    {
      get { return _distance != null; }
      set { if (value == (_distance== null)) _distance = value ? distance : (double?)null; }
    }
    private bool ShouldSerializedistance() { return distanceSpecified; }
    private void Resetdistance() { distanceSpecified = false; }
    

    private double? _gpsSpeed;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gpsSpeed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double gpsSpeed
    {
      get { return _gpsSpeed?? default(double); }
      set { _gpsSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool gpsSpeedSpecified
    {
      get { return _gpsSpeed != null; }
      set { if (value == (_gpsSpeed== null)) _gpsSpeed = value ? gpsSpeed : (double?)null; }
    }
    private bool ShouldSerializegpsSpeed() { return gpsSpeedSpecified; }
    private void ResetgpsSpeed() { gpsSpeedSpecified = false; }
    

    private double? _verticalAccuracymm;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"verticalAccuracymm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double verticalAccuracymm
    {
      get { return _verticalAccuracymm?? default(double); }
      set { _verticalAccuracymm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool verticalAccuracymmSpecified
    {
      get { return _verticalAccuracymm != null; }
      set { if (value == (_verticalAccuracymm== null)) _verticalAccuracymm = value ? verticalAccuracymm : (double?)null; }
    }
    private bool ShouldSerializeverticalAccuracymm() { return verticalAccuracymmSpecified; }
    private void ResetverticalAccuracymm() { verticalAccuracymmSpecified = false; }
    

    private com.deere.proto.EDifferentialType? _DifferentialType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"DifferentialType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDifferentialType DifferentialType
    {
      get { return _DifferentialType?? com.deere.proto.EDifferentialType.DT_UNDEFINED; }
      set { _DifferentialType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DifferentialTypeSpecified
    {
      get { return _DifferentialType != null; }
      set { if (value == (_DifferentialType== null)) _DifferentialType = value ? DifferentialType : (com.deere.proto.EDifferentialType?)null; }
    }
    private bool ShouldSerializeDifferentialType() { return DifferentialTypeSpecified; }
    private void ResetDifferentialType() { DifferentialTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkingStateSample")]
  public partial class ProtoWorkingStateSample : global::ProtoBuf.IExtensible
  {
    public ProtoWorkingStateSample() {}
    

    private uint? _consolidatedWorkingStateID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"consolidatedWorkingStateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint consolidatedWorkingStateID
    {
      get { return _consolidatedWorkingStateID?? default(uint); }
      set { _consolidatedWorkingStateID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool consolidatedWorkingStateIDSpecified
    {
      get { return _consolidatedWorkingStateID != null; }
      set { if (value == (_consolidatedWorkingStateID== null)) _consolidatedWorkingStateID = value ? consolidatedWorkingStateID : (uint?)null; }
    }
    private bool ShouldSerializeconsolidatedWorkingStateID() { return consolidatedWorkingStateIDSpecified; }
    private void ResetconsolidatedWorkingStateID() { consolidatedWorkingStateIDSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.EWorkState> _workState = new global::System.Collections.Generic.List<com.deere.proto.EWorkState>();
    [global::ProtoBuf.ProtoMember(2, Name=@"workState", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<com.deere.proto.EWorkState> workState
    {
      get { return _workState; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkingFunctionDataGroup")]
  public partial class ProtoWorkingFunctionDataGroup : global::ProtoBuf.IExtensible
  {
    public ProtoWorkingFunctionDataGroup() {}
    

    private uint? _functionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"functionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint functionID
    {
      get { return _functionID?? default(uint); }
      set { _functionID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool functionIDSpecified
    {
      get { return _functionID != null; }
      set { if (value == (_functionID== null)) _functionID = value ? functionID : (uint?)null; }
    }
    private bool ShouldSerializefunctionID() { return functionIDSpecified; }
    private void ResetfunctionID() { functionIDSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoRankLocationSample> _rankLocation = new global::System.Collections.Generic.List<com.deere.proto.ProtoRankLocationSample>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rankLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoRankLocationSample> rankLocation
    {
      get { return _rankLocation; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoDataSample> _workingData = new global::System.Collections.Generic.List<com.deere.proto.ProtoDataSample>();
    [global::ProtoBuf.ProtoMember(3, Name=@"workingData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoDataSample> workingData
    {
      get { return _workingData; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoDataSampleUx> _workingDataUx = new global::System.Collections.Generic.List<com.deere.proto.ProtoDataSampleUx>();
    [global::ProtoBuf.ProtoMember(4, Name=@"workingDataUx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoDataSampleUx> workingDataUx
    {
      get { return _workingDataUx; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingStateSample> _workState = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingStateSample>();
    [global::ProtoBuf.ProtoMember(5, Name=@"workState", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingStateSample> workState
    {
      get { return _workState; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoDataEpoch")]
  public partial class ProtoDataEpoch : global::ProtoBuf.IExtensible
  {
    public ProtoDataEpoch() {}
    

    private long? _timestamp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"timestamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long timestamp
    {
      get { return _timestamp?? default(long); }
      set { _timestamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timestampSpecified
    {
      get { return _timestamp != null; }
      set { if (value == (_timestamp== null)) _timestamp = value ? timestamp : (long?)null; }
    }
    private bool ShouldSerializetimestamp() { return timestampSpecified; }
    private void Resettimestamp() { timestampSpecified = false; }
    
    private uint _dataEpochSeq;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dataEpochSeq", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataEpochSeq
    {
      get { return _dataEpochSeq; }
      set { _dataEpochSeq = value; }
    }

    private com.deere.proto.EDataEpochReason? _reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDataEpochReason reason
    {
      get { return _reason?? com.deere.proto.EDataEpochReason.DER_NEW_LOCATION; }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return _reason != null; }
      set { if (value == (_reason== null)) _reason = value ? reason : (com.deere.proto.EDataEpochReason?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunctionDataGroup> _wfData = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunctionDataGroup>();
    [global::ProtoBuf.ProtoMember(4, Name=@"wfData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunctionDataGroup> wfData
    {
      get { return _wfData; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoGPSSample> _gpsSample = new global::System.Collections.Generic.List<com.deere.proto.ProtoGPSSample>();
    [global::ProtoBuf.ProtoMember(6, Name=@"gpsSample", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoGPSSample> gpsSample
    {
      get { return _gpsSample; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}