//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: EquipmentModel.proto
// Note: requires additional types generated from: EquipmentModelCommon.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoOffset")]
  public partial class ProtoOffset : global::ProtoBuf.IExtensible
  {
    public ProtoOffset() {}
    

    private double? _inlineOffset;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"inlineOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double inlineOffset
    {
      get { return _inlineOffset?? default(double); }
      set { _inlineOffset = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool inlineOffsetSpecified
    {
      get { return _inlineOffset != null; }
      set { if (value == (_inlineOffset== null)) _inlineOffset = value ? inlineOffset : (double?)null; }
    }
    private bool ShouldSerializeinlineOffset() { return inlineOffsetSpecified; }
    private void ResetinlineOffset() { inlineOffsetSpecified = false; }
    

    private double? _lateralOffset;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lateralOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double lateralOffset
    {
      get { return _lateralOffset?? default(double); }
      set { _lateralOffset = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lateralOffsetSpecified
    {
      get { return _lateralOffset != null; }
      set { if (value == (_lateralOffset== null)) _lateralOffset = value ? lateralOffset : (double?)null; }
    }
    private bool ShouldSerializelateralOffset() { return lateralOffsetSpecified; }
    private void ResetlateralOffset() { lateralOffsetSpecified = false; }
    

    private double? _height;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"height", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double height
    {
      get { return _height?? default(double); }
      set { _height = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool heightSpecified
    {
      get { return _height != null; }
      set { if (value == (_height== null)) _height = value ? height : (double?)null; }
    }
    private bool ShouldSerializeheight() { return heightSpecified; }
    private void Resetheight() { heightSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoConnection")]
  public partial class ProtoConnection : global::ProtoBuf.IExtensible
  {
    public ProtoConnection() {}
    
    private uint _ConnectionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ConnectionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ConnectionID
    {
      get { return _ConnectionID; }
      set { _ConnectionID = value; }
    }
    private com.deere.proto.ProtoOffset _ConnectionOffset;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ConnectionOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public com.deere.proto.ProtoOffset ConnectionOffset
    {
      get { return _ConnectionOffset; }
      set { _ConnectionOffset = value; }
    }

    private com.deere.proto.EConnectionType? _ConnectionType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ConnectionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EConnectionType ConnectionType
    {
      get { return _ConnectionType?? com.deere.proto.EConnectionType.CT_UNDEFINED; }
      set { _ConnectionType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ConnectionTypeSpecified
    {
      get { return _ConnectionType != null; }
      set { if (value == (_ConnectionType== null)) _ConnectionType = value ? ConnectionType : (com.deere.proto.EConnectionType?)null; }
    }
    private bool ShouldSerializeConnectionType() { return ConnectionTypeSpecified; }
    private void ResetConnectionType() { ConnectionTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoConnectionRelationship")]
  public partial class ProtoConnectionRelationship : global::ProtoBuf.IExtensible
  {
    public ProtoConnectionRelationship() {}
    
    private uint _SourceFrameID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"SourceFrameID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SourceFrameID
    {
      get { return _SourceFrameID; }
      set { _SourceFrameID = value; }
    }

    private uint? _SourceConnectionID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SourceConnectionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SourceConnectionID
    {
      get { return _SourceConnectionID?? default(uint); }
      set { _SourceConnectionID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SourceConnectionIDSpecified
    {
      get { return _SourceConnectionID != null; }
      set { if (value == (_SourceConnectionID== null)) _SourceConnectionID = value ? SourceConnectionID : (uint?)null; }
    }
    private bool ShouldSerializeSourceConnectionID() { return SourceConnectionIDSpecified; }
    private void ResetSourceConnectionID() { SourceConnectionIDSpecified = false; }
    

    private uint? _TargetFrameID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"TargetFrameID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TargetFrameID
    {
      get { return _TargetFrameID?? default(uint); }
      set { _TargetFrameID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TargetFrameIDSpecified
    {
      get { return _TargetFrameID != null; }
      set { if (value == (_TargetFrameID== null)) _TargetFrameID = value ? TargetFrameID : (uint?)null; }
    }
    private bool ShouldSerializeTargetFrameID() { return TargetFrameIDSpecified; }
    private void ResetTargetFrameID() { TargetFrameIDSpecified = false; }
    

    private uint? _TargetConnectionID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"TargetConnectionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TargetConnectionID
    {
      get { return _TargetConnectionID?? default(uint); }
      set { _TargetConnectionID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TargetConnectionIDSpecified
    {
      get { return _TargetConnectionID != null; }
      set { if (value == (_TargetConnectionID== null)) _TargetConnectionID = value ? TargetConnectionID : (uint?)null; }
    }
    private bool ShouldSerializeTargetConnectionID() { return TargetConnectionIDSpecified; }
    private void ResetTargetConnectionID() { TargetConnectionIDSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoRank")]
  public partial class ProtoRank : global::ProtoBuf.IExtensible
  {
    public ProtoRank() {}
    
    private uint _RankID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"RankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RankID
    {
      get { return _RankID; }
      set { _RankID = value; }
    }

    private double? _Width;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Width
    {
      get { return _Width?? default(double); }
      set { _Width = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool WidthSpecified
    {
      get { return _Width != null; }
      set { if (value == (_Width== null)) _Width = value ? Width : (double?)null; }
    }
    private bool ShouldSerializeWidth() { return WidthSpecified; }
    private void ResetWidth() { WidthSpecified = false; }
    

    private com.deere.proto.ProtoOffset _LocalCenter = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"LocalCenter", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoOffset LocalCenter
    {
      get { return _LocalCenter; }
      set { _LocalCenter = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _ElementID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ElementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> ElementID
    {
      get { return _ElementID; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkingElement")]
  public partial class ProtoWorkingElement : global::ProtoBuf.IExtensible
  {
    public ProtoWorkingElement() {}
    
    private uint _elementID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"elementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint elementID
    {
      get { return _elementID; }
      set { _elementID = value; }
    }

    private double? _width;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"width", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double width
    {
      get { return _width?? default(double); }
      set { _width = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool widthSpecified
    {
      get { return _width != null; }
      set { if (value == (_width== null)) _width = value ? width : (double?)null; }
    }
    private bool ShouldSerializewidth() { return widthSpecified; }
    private void Resetwidth() { widthSpecified = false; }
    

    private com.deere.proto.ProtoOffset _centerOffset = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"centerOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoOffset centerOffset
    {
      get { return _centerOffset; }
      set { _centerOffset = value; }
    }

    private bool? _sectionLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sectionLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sectionLevel
    {
      get { return _sectionLevel?? default(bool); }
      set { _sectionLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sectionLevelSpecified
    {
      get { return _sectionLevel != null; }
      set { if (value == (_sectionLevel== null)) _sectionLevel = value ? sectionLevel : (bool?)null; }
    }
    private bool ShouldSerializesectionLevel() { return sectionLevelSpecified; }
    private void ResetsectionLevel() { sectionLevelSpecified = false; }
    

    private bool? _rowLevel;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"rowLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool rowLevel
    {
      get { return _rowLevel?? default(bool); }
      set { _rowLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rowLevelSpecified
    {
      get { return _rowLevel != null; }
      set { if (value == (_rowLevel== null)) _rowLevel = value ? rowLevel : (bool?)null; }
    }
    private bool ShouldSerializerowLevel() { return rowLevelSpecified; }
    private void ResetrowLevel() { rowLevelSpecified = false; }
    

    private bool? _masterLevel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"masterLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool masterLevel
    {
      get { return _masterLevel?? default(bool); }
      set { _masterLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool masterLevelSpecified
    {
      get { return _masterLevel != null; }
      set { if (value == (_masterLevel== null)) _masterLevel = value ? masterLevel : (bool?)null; }
    }
    private bool ShouldSerializemasterLevel() { return masterLevelSpecified; }
    private void ResetmasterLevel() { masterLevelSpecified = false; }
    

    private uint? _consolidatedWorkingStateID;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"consolidatedWorkingStateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint consolidatedWorkingStateID
    {
      get { return _consolidatedWorkingStateID?? default(uint); }
      set { _consolidatedWorkingStateID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool consolidatedWorkingStateIDSpecified
    {
      get { return _consolidatedWorkingStateID != null; }
      set { if (value == (_consolidatedWorkingStateID== null)) _consolidatedWorkingStateID = value ? consolidatedWorkingStateID : (uint?)null; }
    }
    private bool ShouldSerializeconsolidatedWorkingStateID() { return consolidatedWorkingStateIDSpecified; }
    private void ResetconsolidatedWorkingStateID() { consolidatedWorkingStateIDSpecified = false; }
    

    private uint? _parentRankID;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"parentRankID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint parentRankID
    {
      get { return _parentRankID?? default(uint); }
      set { _parentRankID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool parentRankIDSpecified
    {
      get { return _parentRankID != null; }
      set { if (value == (_parentRankID== null)) _parentRankID = value ? parentRankID : (uint?)null; }
    }
    private bool ShouldSerializeparentRankID() { return parentRankIDSpecified; }
    private void ResetparentRankID() { parentRankIDSpecified = false; }
    

    private uint? _parentElementID;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"parentElementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint parentElementID
    {
      get { return _parentElementID?? default(uint); }
      set { _parentElementID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool parentElementIDSpecified
    {
      get { return _parentElementID != null; }
      set { if (value == (_parentElementID== null)) _parentElementID = value ? parentElementID : (uint?)null; }
    }
    private bool ShouldSerializeparentElementID() { return parentElementIDSpecified; }
    private void ResetparentElementID() { parentElementIDSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<uint> _dataID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(10, Name=@"dataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> dataID
    {
      get { return _dataID; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _childElementID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(11, Name=@"childElementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> childElementID
    {
      get { return _childElementID; }
    }
  

    private bool? _meterLevel;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"meterLevel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool meterLevel
    {
      get { return _meterLevel?? default(bool); }
      set { _meterLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool meterLevelSpecified
    {
      get { return _meterLevel != null; }
      set { if (value == (_meterLevel== null)) _meterLevel = value ? meterLevel : (bool?)null; }
    }
    private bool ShouldSerializemeterLevel() { return meterLevelSpecified; }
    private void ResetmeterLevel() { meterLevelSpecified = false; }
    

    private double? _leftFraction;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"leftFraction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double leftFraction
    {
      get { return _leftFraction?? default(double); }
      set { _leftFraction = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leftFractionSpecified
    {
      get { return _leftFraction != null; }
      set { if (value == (_leftFraction== null)) _leftFraction = value ? leftFraction : (double?)null; }
    }
    private bool ShouldSerializeleftFraction() { return leftFractionSpecified; }
    private void ResetleftFraction() { leftFractionSpecified = false; }
    

    private double? _rightFraction;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"rightFraction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double rightFraction
    {
      get { return _rightFraction?? default(double); }
      set { _rightFraction = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rightFractionSpecified
    {
      get { return _rightFraction != null; }
      set { if (value == (_rightFraction== null)) _rightFraction = value ? rightFraction : (double?)null; }
    }
    private bool ShouldSerializerightFraction() { return rightFractionSpecified; }
    private void ResetrightFraction() { rightFractionSpecified = false; }
    

    private double? _sizeFraction;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"sizeFraction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double sizeFraction
    {
      get { return _sizeFraction?? default(double); }
      set { _sizeFraction = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sizeFractionSpecified
    {
      get { return _sizeFraction != null; }
      set { if (value == (_sizeFraction== null)) _sizeFraction = value ? sizeFraction : (double?)null; }
    }
    private bool ShouldSerializesizeFraction() { return sizeFractionSpecified; }
    private void ResetsizeFraction() { sizeFractionSpecified = false; }
    

    private uint? _stateIndex;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"stateIndex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint stateIndex
    {
      get { return _stateIndex?? default(uint); }
      set { _stateIndex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool stateIndexSpecified
    {
      get { return _stateIndex != null; }
      set { if (value == (_stateIndex== null)) _stateIndex = value ? stateIndex : (uint?)null; }
    }
    private bool ShouldSerializestateIndex() { return stateIndexSpecified; }
    private void ResetstateIndex() { stateIndexSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<uint> _propertyDataID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(17, Name=@"propertyDataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> propertyDataID
    {
      get { return _propertyDataID; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkingData")]
  public partial class ProtoWorkingData : global::ProtoBuf.IExtensible
  {
    public ProtoWorkingData() {}
    
    private uint _dataID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataID
    {
      get { return _dataID; }
      set { _dataID = value; }
    }

    private uint? _repDomainID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"repDomainID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint repDomainID
    {
      get { return _repDomainID?? default(uint); }
      set { _repDomainID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool repDomainIDSpecified
    {
      get { return _repDomainID != null; }
      set { if (value == (_repDomainID== null)) _repDomainID = value ? repDomainID : (uint?)null; }
    }
    private bool ShouldSerializerepDomainID() { return repDomainIDSpecified; }
    private void ResetrepDomainID() { repDomainIDSpecified = false; }
    

    private double? _offSet;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double offSet
    {
      get { return _offSet?? default(double); }
      set { _offSet = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool offSetSpecified
    {
      get { return _offSet != null; }
      set { if (value == (_offSet== null)) _offSet = value ? offSet : (double?)null; }
    }
    private bool ShouldSerializeoffSet() { return offSetSpecified; }
    private void ResetoffSet() { offSetSpecified = false; }
    

    private double? _scaleFactor;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scaleFactor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double scaleFactor
    {
      get { return _scaleFactor?? default(double); }
      set { _scaleFactor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scaleFactorSpecified
    {
      get { return _scaleFactor != null; }
      set { if (value == (_scaleFactor== null)) _scaleFactor = value ? scaleFactor : (double?)null; }
    }
    private bool ShouldSerializescaleFactor() { return scaleFactorSpecified; }
    private void ResetscaleFactor() { scaleFactorSpecified = false; }
    

    private string _uom;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uom
    {
      get { return _uom?? ""; }
      set { _uom = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uomSpecified
    {
      get { return _uom != null; }
      set { if (value == (_uom== null)) _uom = value ? uom : (string)null; }
    }
    private bool ShouldSerializeuom() { return uomSpecified; }
    private void Resetuom() { uomSpecified = false; }
    

    private uint? _sampleRate;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sampleRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sampleRate
    {
      get { return _sampleRate?? default(uint); }
      set { _sampleRate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sampleRateSpecified
    {
      get { return _sampleRate != null; }
      set { if (value == (_sampleRate== null)) _sampleRate = value ? sampleRate : (uint?)null; }
    }
    private bool ShouldSerializesampleRate() { return sampleRateSpecified; }
    private void ResetsampleRate() { sampleRateSpecified = false; }
    

    private uint? _Ddi;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Ddi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Ddi
    {
      get { return _Ddi?? default(uint); }
      set { _Ddi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DdiSpecified
    {
      get { return _Ddi != null; }
      set { if (value == (_Ddi== null)) _Ddi = value ? Ddi : (uint?)null; }
    }
    private bool ShouldSerializeDdi() { return DdiSpecified; }
    private void ResetDdi() { DdiSpecified = false; }
    

    private bool? _Controllable;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Controllable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Controllable
    {
      get { return _Controllable?? default(bool); }
      set { _Controllable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ControllableSpecified
    {
      get { return _Controllable != null; }
      set { if (value == (_Controllable== null)) _Controllable = value ? Controllable : (bool?)null; }
    }
    private bool ShouldSerializeControllable() { return ControllableSpecified; }
    private void ResetControllable() { ControllableSpecified = false; }
    

    private double? _appliedLatency;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"appliedLatency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double appliedLatency
    {
      get { return _appliedLatency?? default(double); }
      set { _appliedLatency = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool appliedLatencySpecified
    {
      get { return _appliedLatency != null; }
      set { if (value == (_appliedLatency== null)) _appliedLatency = value ? appliedLatency : (double?)null; }
    }
    private bool ShouldSerializeappliedLatency() { return appliedLatencySpecified; }
    private void ResetappliedLatency() { appliedLatencySpecified = false; }
    

    private double? _expectedLatency;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"expectedLatency", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double expectedLatency
    {
      get { return _expectedLatency?? default(double); }
      set { _expectedLatency = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expectedLatencySpecified
    {
      get { return _expectedLatency != null; }
      set { if (value == (_expectedLatency== null)) _expectedLatency = value ? expectedLatency : (double?)null; }
    }
    private bool ShouldSerializeexpectedLatency() { return expectedLatencySpecified; }
    private void ResetexpectedLatency() { expectedLatencySpecified = false; }
    

    private uint? _calibrationDataID;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"calibrationDataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint calibrationDataID
    {
      get { return _calibrationDataID?? default(uint); }
      set { _calibrationDataID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool calibrationDataIDSpecified
    {
      get { return _calibrationDataID != null; }
      set { if (value == (_calibrationDataID== null)) _calibrationDataID = value ? calibrationDataID : (uint?)null; }
    }
    private bool ShouldSerializecalibrationDataID() { return calibrationDataIDSpecified; }
    private void ResetcalibrationDataID() { calibrationDataIDSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoPropertyData")]
  public partial class ProtoPropertyData : global::ProtoBuf.IExtensible
  {
    public ProtoPropertyData() {}
    
    private uint _dataID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"dataID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataID
    {
      get { return _dataID; }
      set { _dataID = value; }
    }

    private uint? _repDomainID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"repDomainID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint repDomainID
    {
      get { return _repDomainID?? default(uint); }
      set { _repDomainID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool repDomainIDSpecified
    {
      get { return _repDomainID != null; }
      set { if (value == (_repDomainID== null)) _repDomainID = value ? repDomainID : (uint?)null; }
    }
    private bool ShouldSerializerepDomainID() { return repDomainIDSpecified; }
    private void ResetrepDomainID() { repDomainIDSpecified = false; }
    

    private double? _offSet;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"offSet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double offSet
    {
      get { return _offSet?? default(double); }
      set { _offSet = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool offSetSpecified
    {
      get { return _offSet != null; }
      set { if (value == (_offSet== null)) _offSet = value ? offSet : (double?)null; }
    }
    private bool ShouldSerializeoffSet() { return offSetSpecified; }
    private void ResetoffSet() { offSetSpecified = false; }
    

    private double? _scaleFactor;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"scaleFactor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double scaleFactor
    {
      get { return _scaleFactor?? default(double); }
      set { _scaleFactor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scaleFactorSpecified
    {
      get { return _scaleFactor != null; }
      set { if (value == (_scaleFactor== null)) _scaleFactor = value ? scaleFactor : (double?)null; }
    }
    private bool ShouldSerializescaleFactor() { return scaleFactorSpecified; }
    private void ResetscaleFactor() { scaleFactorSpecified = false; }
    

    private string _uom;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"uom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uom
    {
      get { return _uom?? ""; }
      set { _uom = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uomSpecified
    {
      get { return _uom != null; }
      set { if (value == (_uom== null)) _uom = value ? uom : (string)null; }
    }
    private bool ShouldSerializeuom() { return uomSpecified; }
    private void Resetuom() { uomSpecified = false; }
    

    private uint? _Ddi;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Ddi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Ddi
    {
      get { return _Ddi?? default(uint); }
      set { _Ddi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DdiSpecified
    {
      get { return _Ddi != null; }
      set { if (value == (_Ddi== null)) _Ddi = value ? Ddi : (uint?)null; }
    }
    private bool ShouldSerializeDdi() { return DdiSpecified; }
    private void ResetDdi() { DdiSpecified = false; }
    

    private bool? _Controllable;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Controllable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool Controllable
    {
      get { return _Controllable?? default(bool); }
      set { _Controllable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ControllableSpecified
    {
      get { return _Controllable != null; }
      set { if (value == (_Controllable== null)) _Controllable = value ? Controllable : (bool?)null; }
    }
    private bool ShouldSerializeControllable() { return ControllableSpecified; }
    private void ResetControllable() { ControllableSpecified = false; }
    

    private double? _value;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double value
    {
      get { return _value?? default(double); }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool valueSpecified
    {
      get { return _value != null; }
      set { if (value == (_value== null)) _value = value ? _value : (double?)null; }
    }
    private bool ShouldSerializevalue() { return valueSpecified; }
    private void Resetvalue() { valueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoConsolidatedWorkingState")]
  public partial class ProtoConsolidatedWorkingState : global::ProtoBuf.IExtensible
  {
    public ProtoConsolidatedWorkingState() {}
    
    private uint _consolidatedWorkingStateID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"consolidatedWorkingStateID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint consolidatedWorkingStateID
    {
      get { return _consolidatedWorkingStateID; }
      set { _consolidatedWorkingStateID = value; }
    }

    private bool? _controllable;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"controllable", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool controllable
    {
      get { return _controllable?? default(bool); }
      set { _controllable = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool controllableSpecified
    {
      get { return _controllable != null; }
      set { if (value == (_controllable== null)) _controllable = value ? controllable : (bool?)null; }
    }
    private bool ShouldSerializecontrollable() { return controllableSpecified; }
    private void Resetcontrollable() { controllableSpecified = false; }
    

    private uint? _numberOfStates;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"numberOfStates", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint numberOfStates
    {
      get { return _numberOfStates?? default(uint); }
      set { _numberOfStates = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberOfStatesSpecified
    {
      get { return _numberOfStates != null; }
      set { if (value == (_numberOfStates== null)) _numberOfStates = value ? numberOfStates : (uint?)null; }
    }
    private bool ShouldSerializenumberOfStates() { return numberOfStatesSpecified; }
    private void ResetnumberOfStates() { numberOfStatesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkingFunction")]
  public partial class ProtoWorkingFunction : global::ProtoBuf.IExtensible
  {
    public ProtoWorkingFunction() {}
    
    private uint _functionID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"functionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint functionID
    {
      get { return _functionID; }
      set { _functionID = value; }
    }

    private com.deere.proto.EWorkingFunctionType? _workingFunctionType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"workingFunctionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EWorkingFunctionType workingFunctionType
    {
      get { return _workingFunctionType?? com.deere.proto.EWorkingFunctionType.WF_UNDEFINED; }
      set { _workingFunctionType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool workingFunctionTypeSpecified
    {
      get { return _workingFunctionType != null; }
      set { if (value == (_workingFunctionType== null)) _workingFunctionType = value ? workingFunctionType : (com.deere.proto.EWorkingFunctionType?)null; }
    }
    private bool ShouldSerializeworkingFunctionType() { return workingFunctionTypeSpecified; }
    private void ResetworkingFunctionType() { workingFunctionTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoRank> _Ranks = new global::System.Collections.Generic.List<com.deere.proto.ProtoRank>();
    [global::ProtoBuf.ProtoMember(3, Name=@"Ranks", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoRank> Ranks
    {
      get { return _Ranks; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingElement> _Elements = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingElement>();
    [global::ProtoBuf.ProtoMember(4, Name=@"Elements", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingElement> Elements
    {
      get { return _Elements; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingData> _Data = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"Data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingData> Data
    {
      get { return _Data; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoConsolidatedWorkingState> _consolidatedWorkingStates = new global::System.Collections.Generic.List<com.deere.proto.ProtoConsolidatedWorkingState>();
    [global::ProtoBuf.ProtoMember(6, Name=@"consolidatedWorkingStates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoConsolidatedWorkingState> consolidatedWorkingStates
    {
      get { return _consolidatedWorkingStates; }
    }
  

    private string _Key;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key?? ""; }
      set { _Key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool KeySpecified
    {
      get { return _Key != null; }
      set { if (value == (_Key== null)) _Key = value ? Key : (string)null; }
    }
    private bool ShouldSerializeKey() { return KeySpecified; }
    private void ResetKey() { KeySpecified = false; }
    

    private string _Description;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description?? ""; }
      set { _Description = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DescriptionSpecified
    {
      get { return _Description != null; }
      set { if (value == (_Description== null)) _Description = value ? Description : (string)null; }
    }
    private bool ShouldSerializeDescription() { return DescriptionSpecified; }
    private void ResetDescription() { DescriptionSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoPropertyData> _propertyData = new global::System.Collections.Generic.List<com.deere.proto.ProtoPropertyData>();
    [global::ProtoBuf.ProtoMember(10, Name=@"propertyData", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoPropertyData> propertyData
    {
      get { return _propertyData; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoFrame")]
  public partial class ProtoFrame : global::ProtoBuf.IExtensible
  {
    public ProtoFrame() {}
    
    private uint _frameID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"frameID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint frameID
    {
      get { return _frameID; }
      set { _frameID = value; }
    }

    private com.deere.proto.EFrameType? _frameType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"frameType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EFrameType frameType
    {
      get { return _frameType?? com.deere.proto.EFrameType.FT_UNDEFINED; }
      set { _frameType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool frameTypeSpecified
    {
      get { return _frameType != null; }
      set { if (value == (_frameType== null)) _frameType = value ? frameType : (com.deere.proto.EFrameType?)null; }
    }
    private bool ShouldSerializeframeType() { return frameTypeSpecified; }
    private void ResetframeType() { frameTypeSpecified = false; }
    

    private com.deere.proto.EEquipmentType? _equipmentType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipmentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EEquipmentType equipmentType
    {
      get { return _equipmentType?? com.deere.proto.EEquipmentType.ET_UNDEFINED_EQUIPMENT; }
      set { _equipmentType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool equipmentTypeSpecified
    {
      get { return _equipmentType != null; }
      set { if (value == (_equipmentType== null)) _equipmentType = value ? equipmentType : (com.deere.proto.EEquipmentType?)null; }
    }
    private bool ShouldSerializeequipmentType() { return equipmentTypeSpecified; }
    private void ResetequipmentType() { equipmentTypeSpecified = false; }
    

    private string _serialNumber;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"serialNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serialNumber
    {
      get { return _serialNumber?? ""; }
      set { _serialNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serialNumberSpecified
    {
      get { return _serialNumber != null; }
      set { if (value == (_serialNumber== null)) _serialNumber = value ? serialNumber : (string)null; }
    }
    private bool ShouldSerializeserialNumber() { return serialNumberSpecified; }
    private void ResetserialNumber() { serialNumberSpecified = false; }
    

    private string _model;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string model
    {
      get { return _model?? ""; }
      set { _model = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool modelSpecified
    {
      get { return _model != null; }
      set { if (value == (_model== null)) _model = value ? model : (string)null; }
    }
    private bool ShouldSerializemodel() { return modelSpecified; }
    private void Resetmodel() { modelSpecified = false; }
    

    private double? _implementWidth;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"implementWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double implementWidth
    {
      get { return _implementWidth?? default(double); }
      set { _implementWidth = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool implementWidthSpecified
    {
      get { return _implementWidth != null; }
      set { if (value == (_implementWidth== null)) _implementWidth = value ? implementWidth : (double?)null; }
    }
    private bool ShouldSerializeimplementWidth() { return implementWidthSpecified; }
    private void ResetimplementWidth() { implementWidthSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunction> _workingFunctions = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunction>();
    [global::ProtoBuf.ProtoMember(7, Name=@"workingFunctions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkingFunction> workingFunctions
    {
      get { return _workingFunctions; }
    }
  

    private string _Key;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key?? ""; }
      set { _Key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool KeySpecified
    {
      get { return _Key != null; }
      set { if (value == (_Key== null)) _Key = value ? Key : (string)null; }
    }
    private bool ShouldSerializeKey() { return KeySpecified; }
    private void ResetKey() { KeySpecified = false; }
    

    private string _Description;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description?? ""; }
      set { _Description = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DescriptionSpecified
    {
      get { return _Description != null; }
      set { if (value == (_Description== null)) _Description = value ? Description : (string)null; }
    }
    private bool ShouldSerializeDescription() { return DescriptionSpecified; }
    private void ResetDescription() { DescriptionSpecified = false; }
    

    private string _OutOfBoxName;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"OutOfBoxName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string OutOfBoxName
    {
      get { return _OutOfBoxName?? ""; }
      set { _OutOfBoxName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool OutOfBoxNameSpecified
    {
      get { return _OutOfBoxName != null; }
      set { if (value == (_OutOfBoxName== null)) _OutOfBoxName = value ? OutOfBoxName : (string)null; }
    }
    private bool ShouldSerializeOutOfBoxName() { return OutOfBoxNameSpecified; }
    private void ResetOutOfBoxName() { OutOfBoxNameSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoConnection> _Connections = new global::System.Collections.Generic.List<com.deere.proto.ProtoConnection>();
    [global::ProtoBuf.ProtoMember(11, Name=@"Connections", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoConnection> Connections
    {
      get { return _Connections; }
    }
  

    private ulong? _ReleaseDate;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ReleaseDate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong ReleaseDate
    {
      get { return _ReleaseDate?? default(ulong); }
      set { _ReleaseDate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReleaseDateSpecified
    {
      get { return _ReleaseDate != null; }
      set { if (value == (_ReleaseDate== null)) _ReleaseDate = value ? ReleaseDate : (ulong?)null; }
    }
    private bool ShouldSerializeReleaseDate() { return ReleaseDateSpecified; }
    private void ResetReleaseDate() { ReleaseDateSpecified = false; }
    

    private ulong? _LastModifiedDate;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"LastModifiedDate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong LastModifiedDate
    {
      get { return _LastModifiedDate?? default(ulong); }
      set { _LastModifiedDate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LastModifiedDateSpecified
    {
      get { return _LastModifiedDate != null; }
      set { if (value == (_LastModifiedDate== null)) _LastModifiedDate = value ? LastModifiedDate : (ulong?)null; }
    }
    private bool ShouldSerializeLastModifiedDate() { return LastModifiedDateSpecified; }
    private void ResetLastModifiedDate() { LastModifiedDateSpecified = false; }
    

    private string _GPS;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"GPS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GPS
    {
      get { return _GPS?? ""; }
      set { _GPS = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GPSSpecified
    {
      get { return _GPS != null; }
      set { if (value == (_GPS== null)) _GPS = value ? GPS : (string)null; }
    }
    private bool ShouldSerializeGPS() { return GPSSpecified; }
    private void ResetGPS() { GPSSpecified = false; }
    

    private string _ConfigurationGlobalID;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"ConfigurationGlobalID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ConfigurationGlobalID
    {
      get { return _ConfigurationGlobalID?? ""; }
      set { _ConfigurationGlobalID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ConfigurationGlobalIDSpecified
    {
      get { return _ConfigurationGlobalID != null; }
      set { if (value == (_ConfigurationGlobalID== null)) _ConfigurationGlobalID = value ? ConfigurationGlobalID : (string)null; }
    }
    private bool ShouldSerializeConfigurationGlobalID() { return ConfigurationGlobalIDSpecified; }
    private void ResetConfigurationGlobalID() { ConfigurationGlobalIDSpecified = false; }
    

    private string _Comments;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"Comments", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Comments
    {
      get { return _Comments?? ""; }
      set { _Comments = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CommentsSpecified
    {
      get { return _Comments != null; }
      set { if (value == (_Comments== null)) _Comments = value ? Comments : (string)null; }
    }
    private bool ShouldSerializeComments() { return CommentsSpecified; }
    private void ResetComments() { CommentsSpecified = false; }
    

    private com.deere.proto.ProtoOffset _DropPoint = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"DropPoint", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoOffset DropPoint
    {
      get { return _DropPoint; }
      set { _DropPoint = value; }
    }

    private uint? _GpsID;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"GpsID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GpsID
    {
      get { return _GpsID?? default(uint); }
      set { _GpsID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GpsIDSpecified
    {
      get { return _GpsID != null; }
      set { if (value == (_GpsID== null)) _GpsID = value ? GpsID : (uint?)null; }
    }
    private bool ShouldSerializeGpsID() { return GpsIDSpecified; }
    private void ResetGpsID() { GpsIDSpecified = false; }
    

    private com.deere.proto.ProtoOffset _ReceiverOffset = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"ReceiverOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoOffset ReceiverOffset
    {
      get { return _ReceiverOffset; }
      set { _ReceiverOffset = value; }
    }

    private double? _FrontOffset;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"FrontOffset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double FrontOffset
    {
      get { return _FrontOffset?? default(double); }
      set { _FrontOffset = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FrontOffsetSpecified
    {
      get { return _FrontOffset != null; }
      set { if (value == (_FrontOffset== null)) _FrontOffset = value ? FrontOffset : (double?)null; }
    }
    private bool ShouldSerializeFrontOffset() { return FrontOffsetSpecified; }
    private void ResetFrontOffset() { FrontOffsetSpecified = false; }
    

    private double? _ImplementLength;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"ImplementLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ImplementLength
    {
      get { return _ImplementLength?? default(double); }
      set { _ImplementLength = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ImplementLengthSpecified
    {
      get { return _ImplementLength != null; }
      set { if (value == (_ImplementLength== null)) _ImplementLength = value ? ImplementLength : (double?)null; }
    }
    private bool ShouldSerializeImplementLength() { return ImplementLengthSpecified; }
    private void ResetImplementLength() { ImplementLengthSpecified = false; }
    

    private com.deere.proto.EAxleLocation? _NonSteeringAxle;
    [global::ProtoBuf.ProtoMember(30, IsRequired = false, Name=@"NonSteeringAxle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EAxleLocation NonSteeringAxle
    {
      get { return _NonSteeringAxle?? com.deere.proto.EAxleLocation.AL_UNDEFINED; }
      set { _NonSteeringAxle = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NonSteeringAxleSpecified
    {
      get { return _NonSteeringAxle != null; }
      set { if (value == (_NonSteeringAxle== null)) _NonSteeringAxle = value ? NonSteeringAxle : (com.deere.proto.EAxleLocation?)null; }
    }
    private bool ShouldSerializeNonSteeringAxle() { return NonSteeringAxleSpecified; }
    private void ResetNonSteeringAxle() { NonSteeringAxleSpecified = false; }
    

    private double? _TurnRadius;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"TurnRadius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double TurnRadius
    {
      get { return _TurnRadius?? default(double); }
      set { _TurnRadius = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TurnRadiusSpecified
    {
      get { return _TurnRadius != null; }
      set { if (value == (_TurnRadius== null)) _TurnRadius = value ? TurnRadius : (double?)null; }
    }
    private bool ShouldSerializeTurnRadius() { return TurnRadiusSpecified; }
    private void ResetTurnRadius() { TurnRadiusSpecified = false; }
    

    private double? _TurnSensitivity;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"TurnSensitivity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double TurnSensitivity
    {
      get { return _TurnSensitivity?? default(double); }
      set { _TurnSensitivity = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TurnSensitivitySpecified
    {
      get { return _TurnSensitivity != null; }
      set { if (value == (_TurnSensitivity== null)) _TurnSensitivity = value ? TurnSensitivity : (double?)null; }
    }
    private bool ShouldSerializeTurnSensitivity() { return TurnSensitivitySpecified; }
    private void ResetTurnSensitivity() { TurnSensitivitySpecified = false; }
    

    private double? _PhysicalWidth;
    [global::ProtoBuf.ProtoMember(33, IsRequired = false, Name=@"PhysicalWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PhysicalWidth
    {
      get { return _PhysicalWidth?? default(double); }
      set { _PhysicalWidth = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool PhysicalWidthSpecified
    {
      get { return _PhysicalWidth != null; }
      set { if (value == (_PhysicalWidth== null)) _PhysicalWidth = value ? PhysicalWidth : (double?)null; }
    }
    private bool ShouldSerializePhysicalWidth() { return PhysicalWidthSpecified; }
    private void ResetPhysicalWidth() { PhysicalWidthSpecified = false; }
    

    private double? _PhysicalLength;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"PhysicalLength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PhysicalLength
    {
      get { return _PhysicalLength?? default(double); }
      set { _PhysicalLength = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool PhysicalLengthSpecified
    {
      get { return _PhysicalLength != null; }
      set { if (value == (_PhysicalLength== null)) _PhysicalLength = value ? PhysicalLength : (double?)null; }
    }
    private bool ShouldSerializePhysicalLength() { return PhysicalLengthSpecified; }
    private void ResetPhysicalLength() { PhysicalLengthSpecified = false; }
    

    private double? _RowWidth;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"RowWidth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double RowWidth
    {
      get { return _RowWidth?? default(double); }
      set { _RowWidth = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RowWidthSpecified
    {
      get { return _RowWidth != null; }
      set { if (value == (_RowWidth== null)) _RowWidth = value ? RowWidth : (double?)null; }
    }
    private bool ShouldSerializeRowWidth() { return RowWidthSpecified; }
    private void ResetRowWidth() { RowWidthSpecified = false; }
    

    private uint? _RowCount;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"RowCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RowCount
    {
      get { return _RowCount?? default(uint); }
      set { _RowCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RowCountSpecified
    {
      get { return _RowCount != null; }
      set { if (value == (_RowCount== null)) _RowCount = value ? RowCount : (uint?)null; }
    }
    private bool ShouldSerializeRowCount() { return RowCountSpecified; }
    private void ResetRowCount() { RowCountSpecified = false; }
    

    private bool? _InRowConfiguration;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"InRowConfiguration", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool InRowConfiguration
    {
      get { return _InRowConfiguration?? default(bool); }
      set { _InRowConfiguration = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool InRowConfigurationSpecified
    {
      get { return _InRowConfiguration != null; }
      set { if (value == (_InRowConfiguration== null)) _InRowConfiguration = value ? InRowConfiguration : (bool?)null; }
    }
    private bool ShouldSerializeInRowConfiguration() { return InRowConfigurationSpecified; }
    private void ResetInRowConfiguration() { InRowConfigurationSpecified = false; }
    

    private double? _TrackSpacing;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"TrackSpacing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double TrackSpacing
    {
      get { return _TrackSpacing?? default(double); }
      set { _TrackSpacing = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TrackSpacingSpecified
    {
      get { return _TrackSpacing != null; }
      set { if (value == (_TrackSpacing== null)) _TrackSpacing = value ? TrackSpacing : (double?)null; }
    }
    private bool ShouldSerializeTrackSpacing() { return TrackSpacingSpecified; }
    private void ResetTrackSpacing() { TrackSpacingSpecified = false; }
    

    private double? _WheelBaseAmount;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"WheelBaseAmount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double WheelBaseAmount
    {
      get { return _WheelBaseAmount?? default(double); }
      set { _WheelBaseAmount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool WheelBaseAmountSpecified
    {
      get { return _WheelBaseAmount != null; }
      set { if (value == (_WheelBaseAmount== null)) _WheelBaseAmount = value ? WheelBaseAmount : (double?)null; }
    }
    private bool ShouldSerializeWheelBaseAmount() { return WheelBaseAmountSpecified; }
    private void ResetWheelBaseAmount() { WheelBaseAmountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoGPS")]
  public partial class ProtoGPS : global::ProtoBuf.IExtensible
  {
    public ProtoGPS() {}
    
    private uint _ID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ID
    {
      get { return _ID; }
      set { _ID = value; }
    }

    private string _Key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key?? ""; }
      set { _Key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool KeySpecified
    {
      get { return _Key != null; }
      set { if (value == (_Key== null)) _Key = value ? Key : (string)null; }
    }
    private bool ShouldSerializeKey() { return KeySpecified; }
    private void ResetKey() { KeySpecified = false; }
    

    private com.deere.proto.ProtoOffset _GPSOffset = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"GPSOffset", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoOffset GPSOffset
    {
      get { return _GPSOffset; }
      set { _GPSOffset = value; }
    }

    private uint? _ParentFrameID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"ParentFrameID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ParentFrameID
    {
      get { return _ParentFrameID?? default(uint); }
      set { _ParentFrameID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ParentFrameIDSpecified
    {
      get { return _ParentFrameID != null; }
      set { if (value == (_ParentFrameID== null)) _ParentFrameID = value ? ParentFrameID : (uint?)null; }
    }
    private bool ShouldSerializeParentFrameID() { return ParentFrameIDSpecified; }
    private void ResetParentFrameID() { ParentFrameIDSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoEquipmentModel")]
  public partial class ProtoEquipmentModel : global::ProtoBuf.IExtensible
  {
    public ProtoEquipmentModel() {}
    

    private int? _leadFrameID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"leadFrameID", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int leadFrameID
    {
      get { return _leadFrameID?? default(int); }
      set { _leadFrameID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leadFrameIDSpecified
    {
      get { return _leadFrameID != null; }
      set { if (value == (_leadFrameID== null)) _leadFrameID = value ? leadFrameID : (int?)null; }
    }
    private bool ShouldSerializeleadFrameID() { return leadFrameIDSpecified; }
    private void ResetleadFrameID() { leadFrameIDSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoFrame> _frames = new global::System.Collections.Generic.List<com.deere.proto.ProtoFrame>();
    [global::ProtoBuf.ProtoMember(2, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoFrame> frames
    {
      get { return _frames; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoGPS> _GPSUnits = new global::System.Collections.Generic.List<com.deere.proto.ProtoGPS>();
    [global::ProtoBuf.ProtoMember(3, Name=@"GPSUnits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoGPS> GPSUnits
    {
      get { return _GPSUnits; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoConnectionRelationship> _ConnectionRelationships = new global::System.Collections.Generic.List<com.deere.proto.ProtoConnectionRelationship>();
    [global::ProtoBuf.ProtoMember(4, Name=@"ConnectionRelationships", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoConnectionRelationship> ConnectionRelationships
    {
      get { return _ConnectionRelationships; }
    }
  

    private string _Key;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Key
    {
      get { return _Key?? ""; }
      set { _Key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool KeySpecified
    {
      get { return _Key != null; }
      set { if (value == (_Key== null)) _Key = value ? Key : (string)null; }
    }
    private bool ShouldSerializeKey() { return KeySpecified; }
    private void ResetKey() { KeySpecified = false; }
    

    private com.deere.proto.WorkingStateSource_E? _WorkingStateSource;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"WorkingStateSource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.WorkingStateSource_E WorkingStateSource
    {
      get { return _WorkingStateSource?? com.deere.proto.WorkingStateSource_E.WSS_UNKNOWN; }
      set { _WorkingStateSource = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool WorkingStateSourceSpecified
    {
      get { return _WorkingStateSource != null; }
      set { if (value == (_WorkingStateSource== null)) _WorkingStateSource = value ? WorkingStateSource : (com.deere.proto.WorkingStateSource_E?)null; }
    }
    private bool ShouldSerializeWorkingStateSource() { return WorkingStateSourceSpecified; }
    private void ResetWorkingStateSource() { WorkingStateSourceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EFrameType")]
    public enum EFrameType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FT_UNDEFINED", Value=0)]
      FT_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FT_MACHINE", Value=1)]
      FT_MACHINE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FT_IMPLEMENT", Value=2)]
      FT_IMPLEMENT = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EWorkingFunctionType")]
    public enum EWorkingFunctionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_UNDEFINED", Value=0)]
      WF_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_FERTILIZING", Value=1)]
      WF_FERTILIZING = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_PLANTING", Value=2)]
      WF_PLANTING = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_CROP_PROTECTION", Value=3)]
      WF_CROP_PROTECTION = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_TILLAGE", Value=4)]
      WF_TILLAGE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_BALING", Value=5)]
      WF_BALING = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_MOWING", Value=6)]
      WF_MOWING = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_WRAPPING", Value=7)]
      WF_WRAPPING = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_HARVESTING", Value=8)]
      WF_HARVESTING = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_FORAGE_HARVESTING", Value=9)]
      WF_FORAGE_HARVESTING = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_TRANSPORT", Value=10)]
      WF_TRANSPORT = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WF_SWATHING", Value=11)]
      WF_SWATHING = 11
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EAxleLocation")]
    public enum EAxleLocation
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_UNDEFINED", Value=0)]
      AL_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_FRONT_AXLE", Value=1)]
      AL_FRONT_AXLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AL_REAR_AXLE", Value=2)]
      AL_REAR_AXLE = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EEquipmentType")]
    public enum EEquipmentType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_ROW_CROP_TRACTOR", Value=0)]
      ET_ROW_CROP_TRACTOR = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_TRACK_TRACTOR", Value=1)]
      ET_TRACK_TRACTOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_ARTICULATED_TRACTOR", Value=2)]
      ET_ARTICULATED_TRACTOR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_TRACK_TRACTOR_4WD", Value=3)]
      ET_TRACK_TRACTOR_4WD = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_UNDEFINED_VEHICLE_TYPE", Value=4)]
      ET_UNDEFINED_VEHICLE_TYPE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_UNDEFINED_EQUIPMENT", Value=5)]
      ET_UNDEFINED_EQUIPMENT = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_TRACTOR", Value=6)]
      ET_TRACTOR = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_COMBINE", Value=7)]
      ET_COMBINE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_SPRAYER", Value=8)]
      ET_SPRAYER = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_SPREADER", Value=9)]
      ET_SPREADER = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_SEEDER", Value=10)]
      ET_SEEDER = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_OTHER", Value=11)]
      ET_OTHER = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ET_PLANTER", Value=12)]
      ET_PLANTER = 12
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EConnectionPosition")]
    public enum EConnectionPosition
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CP_UNDEFINED", Value=0)]
      CP_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CP_FRONT", Value=1)]
      CP_FRONT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CP_REAR", Value=2)]
      CP_REAR = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"EConnectionType")]
    public enum EConnectionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_UNDEFINED", Value=0)]
      CT_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_TRACTOR_DRAWBAR", Value=1)]
      CT_TRACTOR_DRAWBAR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_THREE_POINT_HITCH_SEMI_MOUNTED", Value=2)]
      CT_THREE_POINT_HITCH_SEMI_MOUNTED = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_THREE_POINT_HITCH_MOUNTED", Value=3)]
      CT_THREE_POINT_HITCH_MOUNTED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_HITCH_HOOK", Value=4)]
      CT_HITCH_HOOK = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_CLEVIS_COUPLING", Value=5)]
      CT_CLEVIS_COUPLING = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_PITON_TYPE_COUPLING", Value=6)]
      CT_PITON_TYPE_COUPLING = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_CUNA_HITCH", Value=7)]
      CT_CUNA_HITCH = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_BALL_HITCH", Value=8)]
      CT_BALL_HITCH = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CT_THREE_POINT_HITCH_MOUNTED_FRONT", Value=9)]
      CT_THREE_POINT_HITCH_MOUNTED_FRONT = 9
    }
  
}