//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: FileFormat.proto
// Note: requires additional types generated from: PackedTimeSpaceChunk.proto
// Note: requires additional types generated from: SessionContext.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileHeader")]
  public partial class FileHeader : global::ProtoBuf.IExtensible
  {
    public FileHeader() {}
    
    private uint _proto_major_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"proto_major_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_major_version
    {
      get { return _proto_major_version; }
      set { _proto_major_version = value; }
    }

    private uint? _startMarker;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"startMarker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint startMarker
    {
      get { return _startMarker?? default(uint); }
      set { _startMarker = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startMarkerSpecified
    {
      get { return _startMarker != null; }
      set { if (value == (_startMarker== null)) _startMarker = value ? startMarker : (uint?)null; }
    }
    private bool ShouldSerializestartMarker() { return startMarkerSpecified; }
    private void ResetstartMarker() { startMarkerSpecified = false; }
    

    private uint? _proto_minor_version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"proto_minor_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_minor_version
    {
      get { return _proto_minor_version?? default(uint); }
      set { _proto_minor_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool proto_minor_versionSpecified
    {
      get { return _proto_minor_version != null; }
      set { if (value == (_proto_minor_version== null)) _proto_minor_version = value ? proto_minor_version : (uint?)null; }
    }
    private bool ShouldSerializeproto_minor_version() { return proto_minor_versionSpecified; }
    private void Resetproto_minor_version() { proto_minor_versionSpecified = false; }
    

    private string _source_software_major_version;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"source_software_major_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string source_software_major_version
    {
      get { return _source_software_major_version?? ""; }
      set { _source_software_major_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool source_software_major_versionSpecified
    {
      get { return _source_software_major_version != null; }
      set { if (value == (_source_software_major_version== null)) _source_software_major_version = value ? source_software_major_version : (string)null; }
    }
    private bool ShouldSerializesource_software_major_version() { return source_software_major_versionSpecified; }
    private void Resetsource_software_major_version() { source_software_major_versionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RecordLength")]
  public partial class RecordLength : global::ProtoBuf.IExtensible
  {
    public RecordLength() {}
    

    private uint? _length;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"length", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint length
    {
      get { return _length?? default(uint); }
      set { _length = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lengthSpecified
    {
      get { return _length != null; }
      set { if (value == (_length== null)) _length = value ? length : (uint?)null; }
    }
    private bool ShouldSerializelength() { return lengthSpecified; }
    private void Resetlength() { lengthSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FileRecord")]
  public partial class FileRecord : global::ProtoBuf.IExtensible
  {
    public FileRecord() {}
    

    private com.deere.proto.EFileRecordType? _fileRecordType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"fileRecordType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EFileRecordType fileRecordType
    {
      get { return _fileRecordType?? com.deere.proto.EFileRecordType.FRT_SESSION_CONTEXT; }
      set { _fileRecordType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fileRecordTypeSpecified
    {
      get { return _fileRecordType != null; }
      set { if (value == (_fileRecordType== null)) _fileRecordType = value ? fileRecordType : (com.deere.proto.EFileRecordType?)null; }
    }
    private bool ShouldSerializefileRecordType() { return fileRecordTypeSpecified; }
    private void ResetfileRecordType() { fileRecordTypeSpecified = false; }
    
    private uint _RecordBeginIndicator;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RecordBeginIndicator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RecordBeginIndicator
    {
      get { return _RecordBeginIndicator; }
      set { _RecordBeginIndicator = value; }
    }

    private com.deere.proto.FileHeader _header = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.FileHeader header
    {
      get { return _header; }
      set { _header = value; }
    }

    private com.deere.proto.ProtoTimeSpaceChunk _chunk = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chunk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoTimeSpaceChunk chunk
    {
      get { return _chunk; }
      set { _chunk = value; }
    }

    private com.deere.proto.ProtoSessionContext _context = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"context", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoSessionContext context
    {
      get { return _context; }
      set { _context = value; }
    }

    private uint? _FileEndIndicator;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"FileEndIndicator", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FileEndIndicator
    {
      get { return _FileEndIndicator?? default(uint); }
      set { _FileEndIndicator = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FileEndIndicatorSpecified
    {
      get { return _FileEndIndicator != null; }
      set { if (value == (_FileEndIndicator== null)) _FileEndIndicator = value ? FileEndIndicator : (uint?)null; }
    }
    private bool ShouldSerializeFileEndIndicator() { return FileEndIndicatorSpecified; }
    private void ResetFileEndIndicator() { FileEndIndicatorSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EFileRecordType")]
    public enum EFileRecordType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRT_SESSION_CONTEXT", Value=1)]
      FRT_SESSION_CONTEXT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRT_CHUNK", Value=2)]
      FRT_CHUNK = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRT_FILE_HEADER", Value=3)]
      FRT_FILE_HEADER = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FRT_FILE_FOOTER", Value=4)]
      FRT_FILE_FOOTER = 4
    }
  
}