//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: PackedTimeSpaceChunk.proto
// Note: requires additional types generated from: EquipmentModelCommon.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LatLonPairStream")]
  public partial class LatLonPairStream : global::ProtoBuf.IExtensible
  {
    public LatLonPairStream() {}
    

    private double? _start_latitude_left_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start_latitude_left_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_latitude_left_arcdeg_scale1E9
    {
      get { return _start_latitude_left_arcdeg_scale1E9?? default(double); }
      set { _start_latitude_left_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_latitude_left_arcdeg_scale1E9Specified
    {
      get { return _start_latitude_left_arcdeg_scale1E9 != null; }
      set { if (value == (_start_latitude_left_arcdeg_scale1E9== null)) _start_latitude_left_arcdeg_scale1E9 = value ? start_latitude_left_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_latitude_left_arcdeg_scale1E9() { return start_latitude_left_arcdeg_scale1E9Specified; }
    private void Resetstart_latitude_left_arcdeg_scale1E9() { start_latitude_left_arcdeg_scale1E9Specified = false; }
    

    private double? _start_longitude_left_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_longitude_left_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_longitude_left_arcdeg_scale1E9
    {
      get { return _start_longitude_left_arcdeg_scale1E9?? default(double); }
      set { _start_longitude_left_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_longitude_left_arcdeg_scale1E9Specified
    {
      get { return _start_longitude_left_arcdeg_scale1E9 != null; }
      set { if (value == (_start_longitude_left_arcdeg_scale1E9== null)) _start_longitude_left_arcdeg_scale1E9 = value ? start_longitude_left_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_longitude_left_arcdeg_scale1E9() { return start_longitude_left_arcdeg_scale1E9Specified; }
    private void Resetstart_longitude_left_arcdeg_scale1E9() { start_longitude_left_arcdeg_scale1E9Specified = false; }
    

    private double? _start_latitude_right_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start_latitude_right_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_latitude_right_arcdeg_scale1E9
    {
      get { return _start_latitude_right_arcdeg_scale1E9?? default(double); }
      set { _start_latitude_right_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_latitude_right_arcdeg_scale1E9Specified
    {
      get { return _start_latitude_right_arcdeg_scale1E9 != null; }
      set { if (value == (_start_latitude_right_arcdeg_scale1E9== null)) _start_latitude_right_arcdeg_scale1E9 = value ? start_latitude_right_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_latitude_right_arcdeg_scale1E9() { return start_latitude_right_arcdeg_scale1E9Specified; }
    private void Resetstart_latitude_right_arcdeg_scale1E9() { start_latitude_right_arcdeg_scale1E9Specified = false; }
    

    private double? _start_longitude_right_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"start_longitude_right_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_longitude_right_arcdeg_scale1E9
    {
      get { return _start_longitude_right_arcdeg_scale1E9?? default(double); }
      set { _start_longitude_right_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_longitude_right_arcdeg_scale1E9Specified
    {
      get { return _start_longitude_right_arcdeg_scale1E9 != null; }
      set { if (value == (_start_longitude_right_arcdeg_scale1E9== null)) _start_longitude_right_arcdeg_scale1E9 = value ? start_longitude_right_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_longitude_right_arcdeg_scale1E9() { return start_longitude_right_arcdeg_scale1E9Specified; }
    private void Resetstart_longitude_right_arcdeg_scale1E9() { start_longitude_right_arcdeg_scale1E9Specified = false; }
    

    private double? _start_implement_heading_arcdeg_scale10;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"start_implement_heading_arcdeg_scale10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_implement_heading_arcdeg_scale10
    {
      get { return _start_implement_heading_arcdeg_scale10?? default(double); }
      set { _start_implement_heading_arcdeg_scale10 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_implement_heading_arcdeg_scale10Specified
    {
      get { return _start_implement_heading_arcdeg_scale10 != null; }
      set { if (value == (_start_implement_heading_arcdeg_scale10== null)) _start_implement_heading_arcdeg_scale10 = value ? start_implement_heading_arcdeg_scale10 : (double?)null; }
    }
    private bool ShouldSerializestart_implement_heading_arcdeg_scale10() { return start_implement_heading_arcdeg_scale10Specified; }
    private void Resetstart_implement_heading_arcdeg_scale10() { start_implement_heading_arcdeg_scale10Specified = false; }
    

    private double? _start_delta_distance_mm;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"start_delta_distance_mm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_delta_distance_mm
    {
      get { return _start_delta_distance_mm?? default(double); }
      set { _start_delta_distance_mm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_delta_distance_mmSpecified
    {
      get { return _start_delta_distance_mm != null; }
      set { if (value == (_start_delta_distance_mm== null)) _start_delta_distance_mm = value ? start_delta_distance_mm : (double?)null; }
    }
    private bool ShouldSerializestart_delta_distance_mm() { return start_delta_distance_mmSpecified; }
    private void Resetstart_delta_distance_mm() { start_delta_distance_mmSpecified = false; }
    

    private double? _start_speed_m_per_sec_scale1E3;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"start_speed_m_per_sec_scale1E3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_speed_m_per_sec_scale1E3
    {
      get { return _start_speed_m_per_sec_scale1E3?? default(double); }
      set { _start_speed_m_per_sec_scale1E3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_speed_m_per_sec_scale1E3Specified
    {
      get { return _start_speed_m_per_sec_scale1E3 != null; }
      set { if (value == (_start_speed_m_per_sec_scale1E3== null)) _start_speed_m_per_sec_scale1E3 = value ? start_speed_m_per_sec_scale1E3 : (double?)null; }
    }
    private bool ShouldSerializestart_speed_m_per_sec_scale1E3() { return start_speed_m_per_sec_scale1E3Specified; }
    private void Resetstart_speed_m_per_sec_scale1E3() { start_speed_m_per_sec_scale1E3Specified = false; }
    

    private bool? _start_in_reverse;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"start_in_reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool start_in_reverse
    {
      get { return _start_in_reverse?? default(bool); }
      set { _start_in_reverse = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_in_reverseSpecified
    {
      get { return _start_in_reverse != null; }
      set { if (value == (_start_in_reverse== null)) _start_in_reverse = value ? start_in_reverse : (bool?)null; }
    }
    private bool ShouldSerializestart_in_reverse() { return start_in_reverseSpecified; }
    private void Resetstart_in_reverse() { start_in_reverseSpecified = false; }
    

    private com.deere.proto.EDataEpochReason? _start_epoch_reason;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"start_epoch_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDataEpochReason start_epoch_reason
    {
      get { return _start_epoch_reason?? com.deere.proto.EDataEpochReason.DER_NEW_LOCATION; }
      set { _start_epoch_reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_epoch_reasonSpecified
    {
      get { return _start_epoch_reason != null; }
      set { if (value == (_start_epoch_reason== null)) _start_epoch_reason = value ? start_epoch_reason : (com.deere.proto.EDataEpochReason?)null; }
    }
    private bool ShouldSerializestart_epoch_reason() { return start_epoch_reasonSpecified; }
    private void Resetstart_epoch_reason() { start_epoch_reasonSpecified = false; }
    

    private long? _last_sample_time;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"last_sample_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_sample_time
    {
      get { return _last_sample_time?? default(long); }
      set { _last_sample_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool last_sample_timeSpecified
    {
      get { return _last_sample_time != null; }
      set { if (value == (_last_sample_time== null)) _last_sample_time = value ? last_sample_time : (long?)null; }
    }
    private bool ShouldSerializelast_sample_time() { return last_sample_timeSpecified; }
    private void Resetlast_sample_time() { last_sample_timeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _time_delta_ms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"time_delta_ms", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> time_delta_ms
    {
      get { return _time_delta_ms; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason> _epoch_reason = new global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason>();
    [global::ProtoBuf.ProtoMember(16, Name=@"epoch_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason> epoch_reason
    {
      get { return _epoch_reason; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _latitude_left_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(17, Name=@"latitude_left_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> latitude_left_delta_arcdeg_scale1E9
    {
      get { return _latitude_left_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _longitude_left_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(18, Name=@"longitude_left_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> longitude_left_delta_arcdeg_scale1E9
    {
      get { return _longitude_left_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _latitude_right_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(19, Name=@"latitude_right_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> latitude_right_delta_arcdeg_scale1E9
    {
      get { return _latitude_right_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _longitude_right_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(20, Name=@"longitude_right_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> longitude_right_delta_arcdeg_scale1E9
    {
      get { return _longitude_right_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _implement_heading_delta_scale10 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(23, Name=@"implement_heading_delta_scale10", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> implement_heading_delta_scale10
    {
      get { return _implement_heading_delta_scale10; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _speed_delta_m_per_sec_scale1E3 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(25, Name=@"speed_delta_m_per_sec_scale1E3", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> speed_delta_m_per_sec_scale1E3
    {
      get { return _speed_delta_m_per_sec_scale1E3; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _delta_distance_delta_mm = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(26, Name=@"delta_distance_delta_mm", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> delta_distance_delta_mm
    {
      get { return _delta_distance_delta_mm; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _in_reverse = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(29, Name=@"in_reverse", DataFormat = global::ProtoBuf.DataFormat.Default, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<bool> in_reverse
    {
      get { return _in_reverse; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LatLonStream")]
  public partial class LatLonStream : global::ProtoBuf.IExtensible
  {
    public LatLonStream() {}
    

    private double? _start_latitude_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start_latitude_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_latitude_arcdeg_scale1E9
    {
      get { return _start_latitude_arcdeg_scale1E9?? default(double); }
      set { _start_latitude_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_latitude_arcdeg_scale1E9Specified
    {
      get { return _start_latitude_arcdeg_scale1E9 != null; }
      set { if (value == (_start_latitude_arcdeg_scale1E9== null)) _start_latitude_arcdeg_scale1E9 = value ? start_latitude_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_latitude_arcdeg_scale1E9() { return start_latitude_arcdeg_scale1E9Specified; }
    private void Resetstart_latitude_arcdeg_scale1E9() { start_latitude_arcdeg_scale1E9Specified = false; }
    

    private double? _start_longitude_arcdeg_scale1E9;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"start_longitude_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_longitude_arcdeg_scale1E9
    {
      get { return _start_longitude_arcdeg_scale1E9?? default(double); }
      set { _start_longitude_arcdeg_scale1E9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_longitude_arcdeg_scale1E9Specified
    {
      get { return _start_longitude_arcdeg_scale1E9 != null; }
      set { if (value == (_start_longitude_arcdeg_scale1E9== null)) _start_longitude_arcdeg_scale1E9 = value ? start_longitude_arcdeg_scale1E9 : (double?)null; }
    }
    private bool ShouldSerializestart_longitude_arcdeg_scale1E9() { return start_longitude_arcdeg_scale1E9Specified; }
    private void Resetstart_longitude_arcdeg_scale1E9() { start_longitude_arcdeg_scale1E9Specified = false; }
    

    private double? _start_heading_arcdeg_scale10;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start_heading_arcdeg_scale10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_heading_arcdeg_scale10
    {
      get { return _start_heading_arcdeg_scale10?? default(double); }
      set { _start_heading_arcdeg_scale10 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_heading_arcdeg_scale10Specified
    {
      get { return _start_heading_arcdeg_scale10 != null; }
      set { if (value == (_start_heading_arcdeg_scale10== null)) _start_heading_arcdeg_scale10 = value ? start_heading_arcdeg_scale10 : (double?)null; }
    }
    private bool ShouldSerializestart_heading_arcdeg_scale10() { return start_heading_arcdeg_scale10Specified; }
    private void Resetstart_heading_arcdeg_scale10() { start_heading_arcdeg_scale10Specified = false; }
    

    private double? _start_elevation_mm;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"start_elevation_mm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_elevation_mm
    {
      get { return _start_elevation_mm?? default(double); }
      set { _start_elevation_mm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_elevation_mmSpecified
    {
      get { return _start_elevation_mm != null; }
      set { if (value == (_start_elevation_mm== null)) _start_elevation_mm = value ? start_elevation_mm : (double?)null; }
    }
    private bool ShouldSerializestart_elevation_mm() { return start_elevation_mmSpecified; }
    private void Resetstart_elevation_mm() { start_elevation_mmSpecified = false; }
    

    private double? _start_speed_m_per_sec_scale1E3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"start_speed_m_per_sec_scale1E3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_speed_m_per_sec_scale1E3
    {
      get { return _start_speed_m_per_sec_scale1E3?? default(double); }
      set { _start_speed_m_per_sec_scale1E3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_speed_m_per_sec_scale1E3Specified
    {
      get { return _start_speed_m_per_sec_scale1E3 != null; }
      set { if (value == (_start_speed_m_per_sec_scale1E3== null)) _start_speed_m_per_sec_scale1E3 = value ? start_speed_m_per_sec_scale1E3 : (double?)null; }
    }
    private bool ShouldSerializestart_speed_m_per_sec_scale1E3() { return start_speed_m_per_sec_scale1E3Specified; }
    private void Resetstart_speed_m_per_sec_scale1E3() { start_speed_m_per_sec_scale1E3Specified = false; }
    

    private double? _start_vertical_accuracy_mm;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"start_vertical_accuracy_mm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_vertical_accuracy_mm
    {
      get { return _start_vertical_accuracy_mm?? default(double); }
      set { _start_vertical_accuracy_mm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_vertical_accuracy_mmSpecified
    {
      get { return _start_vertical_accuracy_mm != null; }
      set { if (value == (_start_vertical_accuracy_mm== null)) _start_vertical_accuracy_mm = value ? start_vertical_accuracy_mm : (double?)null; }
    }
    private bool ShouldSerializestart_vertical_accuracy_mm() { return start_vertical_accuracy_mmSpecified; }
    private void Resetstart_vertical_accuracy_mm() { start_vertical_accuracy_mmSpecified = false; }
    

    private com.deere.proto.EDataEpochReason? _start_epoch_reason;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"start_epoch_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDataEpochReason start_epoch_reason
    {
      get { return _start_epoch_reason?? com.deere.proto.EDataEpochReason.DER_NEW_LOCATION; }
      set { _start_epoch_reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_epoch_reasonSpecified
    {
      get { return _start_epoch_reason != null; }
      set { if (value == (_start_epoch_reason== null)) _start_epoch_reason = value ? start_epoch_reason : (com.deere.proto.EDataEpochReason?)null; }
    }
    private bool ShouldSerializestart_epoch_reason() { return start_epoch_reasonSpecified; }
    private void Resetstart_epoch_reason() { start_epoch_reasonSpecified = false; }
    

    private double? _start_delta_distance_mm;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"start_delta_distance_mm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_delta_distance_mm
    {
      get { return _start_delta_distance_mm?? default(double); }
      set { _start_delta_distance_mm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_delta_distance_mmSpecified
    {
      get { return _start_delta_distance_mm != null; }
      set { if (value == (_start_delta_distance_mm== null)) _start_delta_distance_mm = value ? start_delta_distance_mm : (double?)null; }
    }
    private bool ShouldSerializestart_delta_distance_mm() { return start_delta_distance_mmSpecified; }
    private void Resetstart_delta_distance_mm() { start_delta_distance_mmSpecified = false; }
    

    private com.deere.proto.EDifferentialType? _start_differential_type;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"start_differential_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EDifferentialType start_differential_type
    {
      get { return _start_differential_type?? com.deere.proto.EDifferentialType.DT_UNDEFINED; }
      set { _start_differential_type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_differential_typeSpecified
    {
      get { return _start_differential_type != null; }
      set { if (value == (_start_differential_type== null)) _start_differential_type = value ? start_differential_type : (com.deere.proto.EDifferentialType?)null; }
    }
    private bool ShouldSerializestart_differential_type() { return start_differential_typeSpecified; }
    private void Resetstart_differential_type() { start_differential_typeSpecified = false; }
    

    private int? _start_accuracy;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"start_accuracy", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int start_accuracy
    {
      get { return _start_accuracy?? default(int); }
      set { _start_accuracy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_accuracySpecified
    {
      get { return _start_accuracy != null; }
      set { if (value == (_start_accuracy== null)) _start_accuracy = value ? start_accuracy : (int?)null; }
    }
    private bool ShouldSerializestart_accuracy() { return start_accuracySpecified; }
    private void Resetstart_accuracy() { start_accuracySpecified = false; }
    

    private double? _start_yaw_rate_arcdeg_per_sec_scale10;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"start_yaw_rate_arcdeg_per_sec_scale10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_yaw_rate_arcdeg_per_sec_scale10
    {
      get { return _start_yaw_rate_arcdeg_per_sec_scale10?? default(double); }
      set { _start_yaw_rate_arcdeg_per_sec_scale10 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_yaw_rate_arcdeg_per_sec_scale10Specified
    {
      get { return _start_yaw_rate_arcdeg_per_sec_scale10 != null; }
      set { if (value == (_start_yaw_rate_arcdeg_per_sec_scale10== null)) _start_yaw_rate_arcdeg_per_sec_scale10 = value ? start_yaw_rate_arcdeg_per_sec_scale10 : (double?)null; }
    }
    private bool ShouldSerializestart_yaw_rate_arcdeg_per_sec_scale10() { return start_yaw_rate_arcdeg_per_sec_scale10Specified; }
    private void Resetstart_yaw_rate_arcdeg_per_sec_scale10() { start_yaw_rate_arcdeg_per_sec_scale10Specified = false; }
    

    private bool? _start_in_reverse;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"start_in_reverse", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool start_in_reverse
    {
      get { return _start_in_reverse?? default(bool); }
      set { _start_in_reverse = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_in_reverseSpecified
    {
      get { return _start_in_reverse != null; }
      set { if (value == (_start_in_reverse== null)) _start_in_reverse = value ? start_in_reverse : (bool?)null; }
    }
    private bool ShouldSerializestart_in_reverse() { return start_in_reverseSpecified; }
    private void Resetstart_in_reverse() { start_in_reverseSpecified = false; }
    

    private long? _last_sample_time;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"last_sample_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_sample_time
    {
      get { return _last_sample_time?? default(long); }
      set { _last_sample_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool last_sample_timeSpecified
    {
      get { return _last_sample_time != null; }
      set { if (value == (_last_sample_time== null)) _last_sample_time = value ? last_sample_time : (long?)null; }
    }
    private bool ShouldSerializelast_sample_time() { return last_sample_timeSpecified; }
    private void Resetlast_sample_time() { last_sample_timeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _time_delta_ms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"time_delta_ms", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> time_delta_ms
    {
      get { return _time_delta_ms; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason> _epoch_reason = new global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason>();
    [global::ProtoBuf.ProtoMember(11, Name=@"epoch_reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<com.deere.proto.EDataEpochReason> epoch_reason
    {
      get { return _epoch_reason; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _latitude_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(12, Name=@"latitude_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> latitude_delta_arcdeg_scale1E9
    {
      get { return _latitude_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _longitude_delta_arcdeg_scale1E9 = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(13, Name=@"longitude_delta_arcdeg_scale1E9", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> longitude_delta_arcdeg_scale1E9
    {
      get { return _longitude_delta_arcdeg_scale1E9; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _heading_delta_arcdeg_scale10 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(14, Name=@"heading_delta_arcdeg_scale10", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> heading_delta_arcdeg_scale10
    {
      get { return _heading_delta_arcdeg_scale10; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _delta_distance_delta_mm = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(15, Name=@"delta_distance_delta_mm", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> delta_distance_delta_mm
    {
      get { return _delta_distance_delta_mm; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _elevation_delta_mm = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(16, Name=@"elevation_delta_mm", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> elevation_delta_mm
    {
      get { return _elevation_delta_mm; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _vertical_accuracy_delta_mm = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(17, Name=@"vertical_accuracy_delta_mm", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> vertical_accuracy_delta_mm
    {
      get { return _vertical_accuracy_delta_mm; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.EDifferentialType> _differential_type = new global::System.Collections.Generic.List<com.deere.proto.EDifferentialType>();
    [global::ProtoBuf.ProtoMember(18, Name=@"differential_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<com.deere.proto.EDifferentialType> differential_type
    {
      get { return _differential_type; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _accuracy = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(19, Name=@"accuracy", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> accuracy
    {
      get { return _accuracy; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _yaw_rate_delta_arcdeg_per_sec_scale10 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(20, Name=@"yaw_rate_delta_arcdeg_per_sec_scale10", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> yaw_rate_delta_arcdeg_per_sec_scale10
    {
      get { return _yaw_rate_delta_arcdeg_per_sec_scale10; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _speed_delta_m_per_sec_scale1E3 = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(21, Name=@"speed_delta_m_per_sec_scale1E3", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> speed_delta_m_per_sec_scale1E3
    {
      get { return _speed_delta_m_per_sec_scale1E3; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _in_reverse = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(22, Name=@"in_reverse", DataFormat = global::ProtoBuf.DataFormat.Default, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<bool> in_reverse
    {
      get { return _in_reverse; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoWorkStateStatus")]
  public partial class ProtoWorkStateStatus : global::ProtoBuf.IExtensible
  {
    public ProtoWorkStateStatus() {}
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.EWorkState> _state = new global::System.Collections.Generic.List<com.deere.proto.EWorkState>();
    [global::ProtoBuf.ProtoMember(1, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<com.deere.proto.EWorkState> state
    {
      get { return _state; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatusStream")]
  public partial class StatusStream : global::ProtoBuf.IExtensible
  {
    public StatusStream() {}
    

    private com.deere.proto.ProtoWorkStateStatus _start_workstate = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start_workstate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoWorkStateStatus start_workstate
    {
      get { return _start_workstate; }
      set { _start_workstate = value; }
    }

    private long? _last_sample_time;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"last_sample_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_sample_time
    {
      get { return _last_sample_time?? default(long); }
      set { _last_sample_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool last_sample_timeSpecified
    {
      get { return _last_sample_time != null; }
      set { if (value == (_last_sample_time== null)) _last_sample_time = value ? last_sample_time : (long?)null; }
    }
    private bool ShouldSerializelast_sample_time() { return last_sample_timeSpecified; }
    private void Resetlast_sample_time() { last_sample_timeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _time_delta_ms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"time_delta_ms", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> time_delta_ms
    {
      get { return _time_delta_ms; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoWorkStateStatus> _workstate = new global::System.Collections.Generic.List<com.deere.proto.ProtoWorkStateStatus>();
    [global::ProtoBuf.ProtoMember(2, Name=@"workstate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoWorkStateStatus> workstate
    {
      get { return _workstate; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ValueStream")]
  public partial class ValueStream : global::ProtoBuf.IExtensible
  {
    public ValueStream() {}
    

    private double? _start_value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"start_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double start_value
    {
      get { return _start_value?? default(double); }
      set { _start_value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool start_valueSpecified
    {
      get { return _start_value != null; }
      set { if (value == (_start_value== null)) _start_value = value ? start_value : (double?)null; }
    }
    private bool ShouldSerializestart_value() { return start_valueSpecified; }
    private void Resetstart_value() { start_valueSpecified = false; }
    

    private long? _last_sample_time;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"last_sample_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long last_sample_time
    {
      get { return _last_sample_time?? default(long); }
      set { _last_sample_time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool last_sample_timeSpecified
    {
      get { return _last_sample_time != null; }
      set { if (value == (_last_sample_time== null)) _last_sample_time = value ? last_sample_time : (long?)null; }
    }
    private bool ShouldSerializelast_sample_time() { return last_sample_timeSpecified; }
    private void Resetlast_sample_time() { last_sample_timeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<int> _time_delta_ms = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"time_delta_ms", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> time_delta_ms
    {
      get { return _time_delta_ms; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _value_delta = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"value_delta", DataFormat = global::ProtoBuf.DataFormat.ZigZag, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> value_delta
    {
      get { return _value_delta; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoStreamsBlob")]
  public partial class ProtoStreamsBlob : global::ProtoBuf.IExtensible
  {
    public ProtoStreamsBlob() {}
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.E_STREAM_TYPE> _streamType = new global::System.Collections.Generic.List<com.deere.proto.E_STREAM_TYPE>();
    [global::ProtoBuf.ProtoMember(1, Name=@"streamType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<com.deere.proto.E_STREAM_TYPE> streamType
    {
      get { return _streamType; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _streamID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"streamID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<uint> streamID
    {
      get { return _streamID; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _dataByteArray = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(3, Name=@"dataByteArray", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> dataByteArray
    {
      get { return _dataByteArray; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TimeSpaceChunkStatistics")]
  public partial class TimeSpaceChunkStatistics : global::ProtoBuf.IExtensible
  {
    public TimeSpaceChunkStatistics() {}
    
    private readonly global::System.Collections.Generic.List<uint> _statisticID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"statisticID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> statisticID
    {
      get { return _statisticID; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _value = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(2, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> value
    {
      get { return _value; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoTimeSpaceChunk")]
  public partial class ProtoTimeSpaceChunk : global::ProtoBuf.IExtensible
  {
    public ProtoTimeSpaceChunk() {}
    

    private int? _Version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Version
    {
      get { return _Version?? default(int); }
      set { _Version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VersionSpecified
    {
      get { return _Version != null; }
      set { if (value == (_Version== null)) _Version = value ? Version : (int?)null; }
    }
    private bool ShouldSerializeVersion() { return VersionSpecified; }
    private void ResetVersion() { VersionSpecified = false; }
    

    private string _SessionGUID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"SessionGUID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string SessionGUID
    {
      get { return _SessionGUID?? ""; }
      set { _SessionGUID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SessionGUIDSpecified
    {
      get { return _SessionGUID != null; }
      set { if (value == (_SessionGUID== null)) _SessionGUID = value ? SessionGUID : (string)null; }
    }
    private bool ShouldSerializeSessionGUID() { return SessionGUIDSpecified; }
    private void ResetSessionGUID() { SessionGUIDSpecified = false; }
    
    private uint _chunkSeqNum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"chunkSeqNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint chunkSeqNum
    {
      get { return _chunkSeqNum; }
      set { _chunkSeqNum = value; }
    }

    private long? _delta_time_from_session_start;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"delta_time_from_session_start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long delta_time_from_session_start
    {
      get { return _delta_time_from_session_start?? default(long); }
      set { _delta_time_from_session_start = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool delta_time_from_session_startSpecified
    {
      get { return _delta_time_from_session_start != null; }
      set { if (value == (_delta_time_from_session_start== null)) _delta_time_from_session_start = value ? delta_time_from_session_start : (long?)null; }
    }
    private bool ShouldSerializedelta_time_from_session_start() { return delta_time_from_session_startSpecified; }
    private void Resetdelta_time_from_session_start() { delta_time_from_session_startSpecified = false; }
    

    private int? _endTimeDeltams;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"endTimeDeltams", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int endTimeDeltams
    {
      get { return _endTimeDeltams?? default(int); }
      set { _endTimeDeltams = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeDeltamsSpecified
    {
      get { return _endTimeDeltams != null; }
      set { if (value == (_endTimeDeltams== null)) _endTimeDeltams = value ? endTimeDeltams : (int?)null; }
    }
    private bool ShouldSerializeendTimeDeltams() { return endTimeDeltamsSpecified; }
    private void ResetendTimeDeltams() { endTimeDeltamsSpecified = false; }
    

    private com.deere.proto.ProtoGPSPosition _MBRPosLeftBottom = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"MBRPosLeftBottom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition MBRPosLeftBottom
    {
      get { return _MBRPosLeftBottom; }
      set { _MBRPosLeftBottom = value; }
    }

    private com.deere.proto.ProtoGPSPosition _MBRPosRightTop = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"MBRPosRightTop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoGPSPosition MBRPosRightTop
    {
      get { return _MBRPosRightTop; }
      set { _MBRPosRightTop = value; }
    }

    private com.deere.proto.StreamCompressionType? _blobCompressionType;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"blobCompressionType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.StreamCompressionType blobCompressionType
    {
      get { return _blobCompressionType?? com.deere.proto.StreamCompressionType.SC_None; }
      set { _blobCompressionType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool blobCompressionTypeSpecified
    {
      get { return _blobCompressionType != null; }
      set { if (value == (_blobCompressionType== null)) _blobCompressionType = value ? blobCompressionType : (com.deere.proto.StreamCompressionType?)null; }
    }
    private bool ShouldSerializeblobCompressionType() { return blobCompressionTypeSpecified; }
    private void ResetblobCompressionType() { blobCompressionTypeSpecified = false; }
    

    private byte[] _streamsBlob;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"streamsBlob", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] streamsBlob
    {
      get { return _streamsBlob?? null; }
      set { _streamsBlob = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool streamsBlobSpecified
    {
      get { return _streamsBlob != null; }
      set { if (value == (_streamsBlob== null)) _streamsBlob = value ? streamsBlob : (byte[])null; }
    }
    private bool ShouldSerializestreamsBlob() { return streamsBlobSpecified; }
    private void ResetstreamsBlob() { streamsBlobSpecified = false; }
    

    private com.deere.proto.TimeSpaceChunkStatistics _timeSpaceChunkStatistics = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"timeSpaceChunkStatistics", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.TimeSpaceChunkStatistics timeSpaceChunkStatistics
    {
      get { return _timeSpaceChunkStatistics; }
      set { _timeSpaceChunkStatistics = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"StreamCompressionType")]
    public enum StreamCompressionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_None", Value=0)]
      SC_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SC_Z_RLE", Value=1)]
      SC_Z_RLE = 1
    }
  
}