//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ReferenceData.proto
// Note: requires additional types generated from: EquipmentModelCommon.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NamedEntity")]
  public partial class NamedEntity : global::ProtoBuf.IExtensible
  {
    public NamedEntity() {}
    

    private string _erid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"erid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string erid
    {
      get { return _erid?? ""; }
      set { _erid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eridSpecified
    {
      get { return _erid != null; }
      set { if (value == (_erid== null)) _erid = value ? erid : (string)null; }
    }
    private bool ShouldSerializeerid() { return eridSpecified; }
    private void Reseterid() { eridSpecified = false; }
    

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private long? _lastModified;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastModified", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastModified
    {
      get { return _lastModified?? default(long); }
      set { _lastModified = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastModifiedSpecified
    {
      get { return _lastModified != null; }
      set { if (value == (_lastModified== null)) _lastModified = value ? lastModified : (long?)null; }
    }
    private bool ShouldSerializelastModified() { return lastModifiedSpecified; }
    private void ResetlastModified() { lastModifiedSpecified = false; }
    

    private string _sourceNodeERID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sourceNodeERID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sourceNodeERID
    {
      get { return _sourceNodeERID?? ""; }
      set { _sourceNodeERID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceNodeERIDSpecified
    {
      get { return _sourceNodeERID != null; }
      set { if (value == (_sourceNodeERID== null)) _sourceNodeERID = value ? sourceNodeERID : (string)null; }
    }
    private bool ShouldSerializesourceNodeERID() { return sourceNodeERIDSpecified; }
    private void ResetsourceNodeERID() { sourceNodeERIDSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Crop")]
  public partial class Crop : global::ProtoBuf.IExtensible
  {
    public Crop() {}
    

    private uint? _cropID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cropID
    {
      get { return _cropID?? default(uint); }
      set { _cropID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cropIDSpecified
    {
      get { return _cropID != null; }
      set { if (value == (_cropID== null)) _cropID = value ? cropID : (uint?)null; }
    }
    private bool ShouldSerializecropID() { return cropIDSpecified; }
    private void ResetcropID() { cropIDSpecified = false; }
    

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private long? _lastModified;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastModified", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long lastModified
    {
      get { return _lastModified?? default(long); }
      set { _lastModified = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastModifiedSpecified
    {
      get { return _lastModified != null; }
      set { if (value == (_lastModified== null)) _lastModified = value ? lastModified : (long?)null; }
    }
    private bool ShouldSerializelastModified() { return lastModifiedSpecified; }
    private void ResetlastModified() { lastModifiedSpecified = false; }
    

    private string _sourceNodeERID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sourceNodeERID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sourceNodeERID
    {
      get { return _sourceNodeERID?? ""; }
      set { _sourceNodeERID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceNodeERIDSpecified
    {
      get { return _sourceNodeERID != null; }
      set { if (value == (_sourceNodeERID== null)) _sourceNodeERID = value ? sourceNodeERID : (string)null; }
    }
    private bool ShouldSerializesourceNodeERID() { return sourceNodeERIDSpecified; }
    private void ResetsourceNodeERID() { sourceNodeERIDSpecified = false; }
    

    private com.deere.proto.ProtoValueType _cropWeight = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cropWeight", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoValueType cropWeight
    {
      get { return _cropWeight; }
      set { _cropWeight = value; }
    }

    private com.deere.proto.ProtoValueType _standardPayableMoisture = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"standardPayableMoisture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoValueType standardPayableMoisture
    {
      get { return _standardPayableMoisture; }
      set { _standardPayableMoisture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CropSeason")]
  public partial class CropSeason : global::ProtoBuf.IExtensible
  {
    public CropSeason() {}
    

    private string _cropSeasonName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cropSeasonName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cropSeasonName
    {
      get { return _cropSeasonName?? ""; }
      set { _cropSeasonName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cropSeasonNameSpecified
    {
      get { return _cropSeasonName != null; }
      set { if (value == (_cropSeasonName== null)) _cropSeasonName = value ? cropSeasonName : (string)null; }
    }
    private bool ShouldSerializecropSeasonName() { return cropSeasonNameSpecified; }
    private void ResetcropSeasonName() { cropSeasonNameSpecified = false; }
    

    private uint? _cropID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cropID
    {
      get { return _cropID?? default(uint); }
      set { _cropID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cropIDSpecified
    {
      get { return _cropID != null; }
      set { if (value == (_cropID== null)) _cropID = value ? cropID : (uint?)null; }
    }
    private bool ShouldSerializecropID() { return cropIDSpecified; }
    private void ResetcropID() { cropIDSpecified = false; }
    

    private long? _startTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTime
    {
      get { return _startTime?? default(long); }
      set { _startTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeSpecified
    {
      get { return _startTime != null; }
      set { if (value == (_startTime== null)) _startTime = value ? startTime : (long?)null; }
    }
    private bool ShouldSerializestartTime() { return startTimeSpecified; }
    private void ResetstartTime() { startTimeSpecified = false; }
    

    private long? _endTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime?? default(long); }
      set { _endTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeSpecified
    {
      get { return _endTime != null; }
      set { if (value == (_endTime== null)) _endTime = value ? endTime : (long?)null; }
    }
    private bool ShouldSerializeendTime() { return endTimeSpecified; }
    private void ResetendTime() { endTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CropInput")]
  public partial class CropInput : global::ProtoBuf.IExtensible
  {
    public CropInput() {}
    

    private com.deere.proto.NamedEntity _entity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.NamedEntity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }

    private string _brand;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"brand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string brand
    {
      get { return _brand?? ""; }
      set { _brand = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool brandSpecified
    {
      get { return _brand != null; }
      set { if (value == (_brand== null)) _brand = value ? brand : (string)null; }
    }
    private bool ShouldSerializebrand() { return brandSpecified; }
    private void Resetbrand() { brandSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Variety")]
  public partial class Variety : global::ProtoBuf.IExtensible
  {
    public Variety() {}
    

    private com.deere.proto.CropInput _cropInput = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cropInput", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.CropInput cropInput
    {
      get { return _cropInput; }
      set { _cropInput = value; }
    }

    private uint? _cropID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cropID
    {
      get { return _cropID?? default(uint); }
      set { _cropID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cropIDSpecified
    {
      get { return _cropID != null; }
      set { if (value == (_cropID== null)) _cropID = value ? cropID : (uint?)null; }
    }
    private bool ShouldSerializecropID() { return cropIDSpecified; }
    private void ResetcropID() { cropIDSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Client")]
  public partial class Client : global::ProtoBuf.IExtensible
  {
    public Client() {}
    

    private com.deere.proto.NamedEntity _entity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.NamedEntity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Farm")]
  public partial class Farm : global::ProtoBuf.IExtensible
  {
    public Farm() {}
    

    private com.deere.proto.NamedEntity _entity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.NamedEntity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Field")]
  public partial class Field : global::ProtoBuf.IExtensible
  {
    public Field() {}
    

    private com.deere.proto.NamedEntity _entity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"entity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.NamedEntity entity
    {
      get { return _entity; }
      set { _entity = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReferenceDataContext")]
  public partial class ReferenceDataContext : global::ProtoBuf.IExtensible
  {
    public ReferenceDataContext() {}
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.Crop> _crop = new global::System.Collections.Generic.List<com.deere.proto.Crop>();
    [global::ProtoBuf.ProtoMember(1, Name=@"crop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.Crop> crop
    {
      get { return _crop; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.Variety> _variety = new global::System.Collections.Generic.List<com.deere.proto.Variety>();
    [global::ProtoBuf.ProtoMember(2, Name=@"variety", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.Variety> variety
    {
      get { return _variety; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}