//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: SchemaVersion.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SchemaVersionDefaults")]
  public partial class SchemaVersionDefaults : global::ProtoBuf.IExtensible
  {
    public SchemaVersionDefaults() {}
    
    private uint _proto_major_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"proto_major_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_major_version
    {
      get { return _proto_major_version; }
      set { _proto_major_version = value; }
    }
    private uint _proto_minor_version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"proto_minor_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_minor_version
    {
      get { return _proto_minor_version; }
      set { _proto_minor_version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}