//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: SessionContextAck.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoSessionId")]
  public partial class ProtoSessionId : global::ProtoBuf.IExtensible
  {
    public ProtoSessionId() {}
    
    private string _sessionGuid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionGuid
    {
      get { return _sessionGuid; }
      set { _sessionGuid = value; }
    }

    private bool? _sessionComplete;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sessionComplete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool sessionComplete
    {
      get { return _sessionComplete?? default(bool); }
      set { _sessionComplete = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sessionCompleteSpecified
    {
      get { return _sessionComplete != null; }
      set { if (value == (_sessionComplete== null)) _sessionComplete = value ? sessionComplete : (bool?)null; }
    }
    private bool ShouldSerializesessionComplete() { return sessionCompleteSpecified; }
    private void ResetsessionComplete() { sessionCompleteSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoSessionContextAck")]
  public partial class ProtoSessionContextAck : global::ProtoBuf.IExtensible
  {
    public ProtoSessionContextAck() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoSessionId> _sessionIds = new global::System.Collections.Generic.List<com.deere.proto.ProtoSessionId>();
    [global::ProtoBuf.ProtoMember(2, Name=@"sessionIds", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoSessionId> sessionIds
    {
      get { return _sessionIds; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}