//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: SessionContext.proto
// Note: requires additional types generated from: EquipmentModel.proto
// Note: requires additional types generated from: ReferenceData.proto
// Note: requires additional types generated from: Operation.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoVarietyAssignment")]
  public partial class ProtoVarietyAssignment : global::ProtoBuf.IExtensible
  {
    public ProtoVarietyAssignment() {}
    

    private string _erid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"erid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string erid
    {
      get { return _erid?? ""; }
      set { _erid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eridSpecified
    {
      get { return _erid != null; }
      set { if (value == (_erid== null)) _erid = value ? erid : (string)null; }
    }
    private bool ShouldSerializeerid() { return eridSpecified; }
    private void Reseterid() { eridSpecified = false; }
    

    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name?? ""; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return _name != null; }
      set { if (value == (_name== null)) _name = value ? name : (string)null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    

    private string _brandGuid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"brandGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string brandGuid
    {
      get { return _brandGuid?? ""; }
      set { _brandGuid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool brandGuidSpecified
    {
      get { return _brandGuid != null; }
      set { if (value == (_brandGuid== null)) _brandGuid = value ? brandGuid : (string)null; }
    }
    private bool ShouldSerializebrandGuid() { return brandGuidSpecified; }
    private void ResetbrandGuid() { brandGuidSpecified = false; }
    

    private uint? _EICCropID;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"EICCropID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EICCropID
    {
      get { return _EICCropID?? default(uint); }
      set { _EICCropID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool EICCropIDSpecified
    {
      get { return _EICCropID != null; }
      set { if (value == (_EICCropID== null)) _EICCropID = value ? EICCropID : (uint?)null; }
    }
    private bool ShouldSerializeEICCropID() { return EICCropIDSpecified; }
    private void ResetEICCropID() { EICCropIDSpecified = false; }
    

    private uint? _functionID;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"functionID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint functionID
    {
      get { return _functionID?? default(uint); }
      set { _functionID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool functionIDSpecified
    {
      get { return _functionID != null; }
      set { if (value == (_functionID== null)) _functionID = value ? functionID : (uint?)null; }
    }
    private bool ShouldSerializefunctionID() { return functionIDSpecified; }
    private void ResetfunctionID() { functionIDSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<uint> _rowelementID = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"rowelementID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> rowelementID
    {
      get { return _rowelementID; }
    }
  

    private uint? _colorSpace;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"colorSpace", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint colorSpace
    {
      get { return _colorSpace?? default(uint); }
      set { _colorSpace = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool colorSpaceSpecified
    {
      get { return _colorSpace != null; }
      set { if (value == (_colorSpace== null)) _colorSpace = value ? colorSpace : (uint?)null; }
    }
    private bool ShouldSerializecolorSpace() { return colorSpaceSpecified; }
    private void ResetcolorSpace() { colorSpaceSpecified = false; }
    

    private uint? _color;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint color
    {
      get { return _color?? default(uint); }
      set { _color = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool colorSpecified
    {
      get { return _color != null; }
      set { if (value == (_color== null)) _color = value ? color : (uint?)null; }
    }
    private bool ShouldSerializecolor() { return colorSpecified; }
    private void Resetcolor() { colorSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoSimplePlantingContext")]
  public partial class ProtoSimplePlantingContext : global::ProtoBuf.IExtensible
  {
    public ProtoSimplePlantingContext() {}
    
    private readonly global::System.Collections.Generic.List<com.deere.proto.NamedEntity> _brand = new global::System.Collections.Generic.List<com.deere.proto.NamedEntity>();
    [global::ProtoBuf.ProtoMember(2, Name=@"brand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.NamedEntity> brand
    {
      get { return _brand; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.Crop> _crop = new global::System.Collections.Generic.List<com.deere.proto.Crop>();
    [global::ProtoBuf.ProtoMember(3, Name=@"crop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.Crop> crop
    {
      get { return _crop; }
    }
  
    private readonly global::System.Collections.Generic.List<com.deere.proto.ProtoVarietyAssignment> _varietyAssignment = new global::System.Collections.Generic.List<com.deere.proto.ProtoVarietyAssignment>();
    [global::ProtoBuf.ProtoMember(4, Name=@"varietyAssignment", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.ProtoVarietyAssignment> varietyAssignment
    {
      get { return _varietyAssignment; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatisticalContext")]
  public partial class StatisticalContext : global::ProtoBuf.IExtensible
  {
    public StatisticalContext() {}
    

    private uint? _statisticID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"statisticID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint statisticID
    {
      get { return _statisticID?? default(uint); }
      set { _statisticID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool statisticIDSpecified
    {
      get { return _statisticID != null; }
      set { if (value == (_statisticID== null)) _statisticID = value ? statisticID : (uint?)null; }
    }
    private bool ShouldSerializestatisticID() { return statisticIDSpecified; }
    private void ResetstatisticID() { statisticIDSpecified = false; }
    

    private uint? _repDomainID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"repDomainID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint repDomainID
    {
      get { return _repDomainID?? default(uint); }
      set { _repDomainID = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool repDomainIDSpecified
    {
      get { return _repDomainID != null; }
      set { if (value == (_repDomainID== null)) _repDomainID = value ? repDomainID : (uint?)null; }
    }
    private bool ShouldSerializerepDomainID() { return repDomainIDSpecified; }
    private void ResetrepDomainID() { repDomainIDSpecified = false; }
    

    private uint? _Ddi;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Ddi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Ddi
    {
      get { return _Ddi?? default(uint); }
      set { _Ddi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DdiSpecified
    {
      get { return _Ddi != null; }
      set { if (value == (_Ddi== null)) _Ddi = value ? Ddi : (uint?)null; }
    }
    private bool ShouldSerializeDdi() { return DdiSpecified; }
    private void ResetDdi() { DdiSpecified = false; }
    

    private string _uom;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"uom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uom
    {
      get { return _uom?? ""; }
      set { _uom = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool uomSpecified
    {
      get { return _uom != null; }
      set { if (value == (_uom== null)) _uom = value ? uom : (string)null; }
    }
    private bool ShouldSerializeuom() { return uomSpecified; }
    private void Resetuom() { uomSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoSessionContext")]
  public partial class ProtoSessionContext : global::ProtoBuf.IExtensible
  {
    public ProtoSessionContext() {}
    
    private uint _proto_major_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"proto_major_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_major_version
    {
      get { return _proto_major_version; }
      set { _proto_major_version = value; }
    }
    private string _sessionGuid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sessionGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionGuid
    {
      get { return _sessionGuid; }
      set { _sessionGuid = value; }
    }

    private long? _startTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"startTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long startTime
    {
      get { return _startTime?? default(long); }
      set { _startTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool startTimeSpecified
    {
      get { return _startTime != null; }
      set { if (value == (_startTime== null)) _startTime = value ? startTime : (long?)null; }
    }
    private bool ShouldSerializestartTime() { return startTimeSpecified; }
    private void ResetstartTime() { startTimeSpecified = false; }
    

    private com.deere.proto.ESourceType? _sourceType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sourceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.ESourceType sourceType
    {
      get { return _sourceType?? com.deere.proto.ESourceType.ST_2630; }
      set { _sourceType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceTypeSpecified
    {
      get { return _sourceType != null; }
      set { if (value == (_sourceType== null)) _sourceType = value ? sourceType : (com.deere.proto.ESourceType?)null; }
    }
    private bool ShouldSerializesourceType() { return sourceTypeSpecified; }
    private void ResetsourceType() { sourceTypeSpecified = false; }
    

    private string _sourceSerialNumber;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sourceSerialNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sourceSerialNumber
    {
      get { return _sourceSerialNumber?? ""; }
      set { _sourceSerialNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceSerialNumberSpecified
    {
      get { return _sourceSerialNumber != null; }
      set { if (value == (_sourceSerialNumber== null)) _sourceSerialNumber = value ? sourceSerialNumber : (string)null; }
    }
    private bool ShouldSerializesourceSerialNumber() { return sourceSerialNumberSpecified; }
    private void ResetsourceSerialNumber() { sourceSerialNumberSpecified = false; }
    

    private string _sourceNodeGuid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sourceNodeGuid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sourceNodeGuid
    {
      get { return _sourceNodeGuid?? ""; }
      set { _sourceNodeGuid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool sourceNodeGuidSpecified
    {
      get { return _sourceNodeGuid != null; }
      set { if (value == (_sourceNodeGuid== null)) _sourceNodeGuid = value ? sourceNodeGuid : (string)null; }
    }
    private bool ShouldSerializesourceNodeGuid() { return sourceNodeGuidSpecified; }
    private void ResetsourceNodeGuid() { sourceNodeGuidSpecified = false; }
    

    private uint? _endTimeDelta;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"endTimeDelta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint endTimeDelta
    {
      get { return _endTimeDelta?? default(uint); }
      set { _endTimeDelta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeDeltaSpecified
    {
      get { return _endTimeDelta != null; }
      set { if (value == (_endTimeDelta== null)) _endTimeDelta = value ? endTimeDelta : (uint?)null; }
    }
    private bool ShouldSerializeendTimeDelta() { return endTimeDeltaSpecified; }
    private void ResetendTimeDelta() { endTimeDeltaSpecified = false; }
    

    private uint? _chunkCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"chunkCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint chunkCount
    {
      get { return _chunkCount?? default(uint); }
      set { _chunkCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool chunkCountSpecified
    {
      get { return _chunkCount != null; }
      set { if (value == (_chunkCount== null)) _chunkCount = value ? chunkCount : (uint?)null; }
    }
    private bool ShouldSerializechunkCount() { return chunkCountSpecified; }
    private void ResetchunkCount() { chunkCountSpecified = false; }
    

    private uint? _dataEpochCount;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dataEpochCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataEpochCount
    {
      get { return _dataEpochCount?? default(uint); }
      set { _dataEpochCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataEpochCountSpecified
    {
      get { return _dataEpochCount != null; }
      set { if (value == (_dataEpochCount== null)) _dataEpochCount = value ? dataEpochCount : (uint?)null; }
    }
    private bool ShouldSerializedataEpochCount() { return dataEpochCountSpecified; }
    private void ResetdataEpochCount() { dataEpochCountSpecified = false; }
    

    private com.deere.proto.ProtoEquipmentModel _equipmentModel = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"equipmentModel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoEquipmentModel equipmentModel
    {
      get { return _equipmentModel; }
      set { _equipmentModel = value; }
    }

    private com.deere.proto.Client _client = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"client", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.Client client
    {
      get { return _client; }
      set { _client = value; }
    }

    private com.deere.proto.Farm _farm = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"farm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.Farm farm
    {
      get { return _farm; }
      set { _farm = value; }
    }

    private com.deere.proto.Field _field = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"field", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.Field field
    {
      get { return _field; }
      set { _field = value; }
    }

    private com.deere.proto.NamedEntity _equipmentOperator = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"equipmentOperator", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.NamedEntity equipmentOperator
    {
      get { return _equipmentOperator; }
      set { _equipmentOperator = value; }
    }

    private com.deere.proto.ProtoSimplePlantingContext _simplePlantingContext = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"simplePlantingContext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoSimplePlantingContext simplePlantingContext
    {
      get { return _simplePlantingContext; }
      set { _simplePlantingContext = value; }
    }

    private bool? _ackedToMyJD;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ackedToMyJD", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ackedToMyJD
    {
      get { return _ackedToMyJD?? default(bool); }
      set { _ackedToMyJD = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ackedToMyJDSpecified
    {
      get { return _ackedToMyJD != null; }
      set { if (value == (_ackedToMyJD== null)) _ackedToMyJD = value ? ackedToMyJD : (bool?)null; }
    }
    private bool ShouldSerializeackedToMyJD() { return ackedToMyJDSpecified; }
    private void ResetackedToMyJD() { ackedToMyJDSpecified = false; }
    

    private uint? _cropYear;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"cropYear", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cropYear
    {
      get { return _cropYear?? default(uint); }
      set { _cropYear = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool cropYearSpecified
    {
      get { return _cropYear != null; }
      set { if (value == (_cropYear== null)) _cropYear = value ? cropYear : (uint?)null; }
    }
    private bool ShouldSerializecropYear() { return cropYearSpecified; }
    private void ResetcropYear() { cropYearSpecified = false; }
    

    private com.deere.proto.OperationsContext _operationsContext = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"operationsContext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.OperationsContext operationsContext
    {
      get { return _operationsContext; }
      set { _operationsContext = value; }
    }

    private com.deere.proto.ReferenceDataContext _referenceDataContext = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"referenceDataContext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ReferenceDataContext referenceDataContext
    {
      get { return _referenceDataContext; }
      set { _referenceDataContext = value; }
    }
    private readonly global::System.Collections.Generic.List<com.deere.proto.StatisticalContext> _statisticalContext = new global::System.Collections.Generic.List<com.deere.proto.StatisticalContext>();
    [global::ProtoBuf.ProtoMember(22, Name=@"statisticalContext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<com.deere.proto.StatisticalContext> statisticalContext
    {
      get { return _statisticalContext; }
    }
  

    private uint? _proto_minor_version;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"proto_minor_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint proto_minor_version
    {
      get { return _proto_minor_version?? default(uint); }
      set { _proto_minor_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool proto_minor_versionSpecified
    {
      get { return _proto_minor_version != null; }
      set { if (value == (_proto_minor_version== null)) _proto_minor_version = value ? proto_minor_version : (uint?)null; }
    }
    private bool ShouldSerializeproto_minor_version() { return proto_minor_versionSpecified; }
    private void Resetproto_minor_version() { proto_minor_versionSpecified = false; }
    

    private string _source_software_major_version;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"source_software_major_version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string source_software_major_version
    {
      get { return _source_software_major_version?? ""; }
      set { _source_software_major_version = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool source_software_major_versionSpecified
    {
      get { return _source_software_major_version != null; }
      set { if (value == (_source_software_major_version== null)) _source_software_major_version = value ? source_software_major_version : (string)null; }
    }
    private bool ShouldSerializesource_software_major_version() { return source_software_major_versionSpecified; }
    private void Resetsource_software_major_version() { source_software_major_versionSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ESourceType")]
    public enum ESourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_2630", Value=1)]
      ST_2630 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_GSix", Value=2)]
      ST_GSix = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_BlackBox", Value=3)]
      ST_BlackBox = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_MJD", Value=4)]
      ST_MJD = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ST_ApexLegacy", Value=5)]
      ST_ApexLegacy = 5
    }
  
}