//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: wire format proposal.proto
// Note: requires additional types generated from: PackedTimeSpaceChunk.proto
// Note: requires additional types generated from: SessionContext.proto
// Note: requires additional types generated from: DataEpoch.proto
namespace com.deere.proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ProtoOnTheWireMessage")]
  public partial class ProtoOnTheWireMessage : global::ProtoBuf.IExtensible
  {
    public ProtoOnTheWireMessage() {}
    
    private uint _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint version
    {
      get { return _version; }
      set { _version = value; }
    }

    private com.deere.proto.EProtoWireMessageType? _messageType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"messageType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public com.deere.proto.EProtoWireMessageType messageType
    {
      get { return _messageType?? com.deere.proto.EProtoWireMessageType.PW_PROTO_SESSION_CONTEXT; }
      set { _messageType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool messageTypeSpecified
    {
      get { return _messageType != null; }
      set { if (value == (_messageType== null)) _messageType = value ? messageType : (com.deere.proto.EProtoWireMessageType?)null; }
    }
    private bool ShouldSerializemessageType() { return messageTypeSpecified; }
    private void ResetmessageType() { messageTypeSpecified = false; }
    

    private com.deere.proto.ProtoSessionContext _sessionContext = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sessionContext", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoSessionContext sessionContext
    {
      get { return _sessionContext; }
      set { _sessionContext = value; }
    }

    private com.deere.proto.ProtoDataEpoch _dataEpoch = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dataEpoch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public com.deere.proto.ProtoDataEpoch dataEpoch
    {
      get { return _dataEpoch; }
      set { _dataEpoch = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"EProtoWireMessageType")]
    public enum EProtoWireMessageType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PW_PROTO_SESSION_CONTEXT", Value=1)]
      PW_PROTO_SESSION_CONTEXT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PW_PROTO_DATA_EPOCH", Value=2)]
      PW_PROTO_DATA_EPOCH = 2
    }
  
}