//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulationDataLayer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omudcknnkm.database.windows.net;Initial Catalog=SimulationDB;User ID=" +
            "simulation")]
        public string SimulationDBConnectionString {
            get {
                return ((string)(this["SimulationDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omudcknnkm.database.windows.net;Initial Catalog=SimulationDB;User ID=" +
            "simulation;Password=Cennest123")]
        public string SimulationDBConnectionString1 {
            get {
                return ((string)(this["SimulationDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.4\\SQLEXPRESS;Initial Catalog=SimulationDB;Integrated Securi" +
            "ty=True")]
        public string SimulationDBConnectionString2 {
            get {
                return ((string)(this["SimulationDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.4\\SQLEXPRESS;Initial Catalog=SimulationDB;Integrated Securi" +
            "ty=True")]
        public string SimulationDBConnectionString3 {
            get {
                return ((string)(this["SimulationDBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRADEEP-PC;Initial Catalog=SimulationDB;User ID=pradeep;Password=vish" +
            "wa89")]
        public string SimulationDBConnectionString4 {
            get {
                return ((string)(this["SimulationDBConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=SimulationDB;User ID=pradeep;Password=vishwa89")]
        public string SimulationDBConnectionString5 {
            get {
                return ((string)(this["SimulationDBConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omudcknnkm.database.windows.net;Initial Catalog=IntegrationDB;User ID" +
            "=simulation;Password=Cennest123")]
        public string IntegrationDBConnectionString {
            get {
                return ((string)(this["IntegrationDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omudcknnkm.database.windows.net;Initial Catalog=DeereSimulationDB;Use" +
            "r ID=simulation;Password=Cennest123")]
        public string DeereSimulationDBConnectionString {
            get {
                return ((string)(this["DeereSimulationDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=omudcknnkm.database.windows.net;Initial Catalog=HongTestDB;User ID=si" +
            "mulation;Password=Cennest123")]
        public string HongTestDBConnectionString {
            get {
                return ((string)(this["HongTestDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=anshuleeDB;User ID=si" +
            "mulation;Password=Cennest123")]
        public string anshuleeDBConnectionString {
            get {
                return ((string)(this["anshuleeDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hitesh-pc\\sqlexpress;Initial Catalog=SimulationDB;Integrated Security" +
            "=True")]
        public string SimulationDBConnectionString6 {
            get {
                return ((string)(this["SimulationDBConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test8DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test8DBConnectionString {
            get {
                return ((string)(this["Test8DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=anshuleeDB;Persist Se" +
            "curity Info=True;User ID=simulation;Password=Cennest123")]
        public string anshuleeDBConnectionString1 {
            get {
                return ((string)(this["anshuleeDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test2DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test2DBConnectionString {
            get {
                return ((string)(this["Test2DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test3DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test3DBConnectionString {
            get {
                return ((string)(this["Test3DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test6DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test6DBConnectionString {
            get {
                return ((string)(this["Test6DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test7DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test7DBConnectionString {
            get {
                return ((string)(this["Test7DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test1DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test1DBConnectionString {
            get {
                return ((string)(this["Test1DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=Test5DB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string Test5DBConnectionString {
            get {
                return ((string)(this["Test5DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=hitesH-PC\\sqlexpress;Initial Catalog=SimulationDB;Integrated Security" +
            "=True")]
        public string SimulationDBConnectionString7 {
            get {
                return ((string)(this["SimulationDBConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestDB;User ID=sim" +
            "ulation;Password=Cennest123")]
        public string HarvestDBConnectionString {
            get {
                return ((string)(this["HarvestDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=FieldTestDB;User ID=s" +
            "imulation;Password=Cennest123")]
        public string FieldTestDBConnectionString {
            get {
                return ((string)(this["FieldTestDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.5;Initial Catalog=DataSimulator;Integrated Security=True")]
        public string DataSimulatorConnectionString {
            get {
                return ((string)(this["DataSimulatorConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.5;Initial Catalog=HarvestDB;Integrated Security=True")]
        public string HarvestDBConnectionString1 {
            get {
                return ((string)(this["HarvestDBConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NILESH-PC;Initial Catalog=HarvestDB;User ID=cennest;Password=cennest")]
        public string HarvestDBConnectionString2 {
            get {
                return ((string)(this["HarvestDBConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ADMIN-PC\\SQLEXPRESS;Initial Catalog=HarvestDB;Integrated Security=Tru" +
            "e")]
        public string HarvestDBConnectionString4 {
            get {
                return ((string)(this["HarvestDBConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestDB;User ID=sim" +
            "ulation")]
        public string HarvestDBConnectionString5 {
            get {
                return ((string)(this["HarvestDBConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestDBTest1;User I" +
            "D=simulation;Password=Cennest123")]
        public string HarvestDBTest1ConnectionString {
            get {
                return ((string)(this["HarvestDBTest1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestTest2DB;User I" +
            "D=simulation;Password=Cennest123")]
        public string HarvestTest2DBConnectionString {
            get {
                return ((string)(this["HarvestTest2DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestTest3DB;User I" +
            "D=simulation;Password=Cennest123")]
        public string HarvestTest3DBConnectionString {
            get {
                return ((string)(this["HarvestTest3DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=HarvestTest4DB;User I" +
            "D=simulation;Password=Cennest123")]
        public string HarvestTest4DBConnectionString {
            get {
                return ((string)(this["HarvestTest4DBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.17;Initial Catalog=HarvestDB;User ID=cennest;Password=cenne" +
            "st")]
        public string HarvestDBConnectionString3 {
            get {
                return ((string)(this["HarvestDBConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=HarvestDB;Integrated Security=True")]
        public string HarvestDBConnectionString6 {
            get {
                return ((string)(this["HarvestDBConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=kawk90h1kb.database.windows.net;Initial Catalog=COPBRDB;User ID=simul" +
            "ation;Password=Cennest123")]
        public string COPBRDBConnectionString {
            get {
                return ((string)(this["COPBRDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRADEEP-PC;Initial Catalog=HarvestTest2DB;User ID=cennest;Password=ce" +
            "nnest")]
        public string HarvestTest2DBConnectionString1 {
            get {
                return ((string)(this["HarvestTest2DBConnectionString1"]));
            }
        }
    }
}
